webtalk_init -webtalk_dir D:\\SMartCart\\hdl_prj\\vivado_ip_prj\\vivado_prj.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Вт ноя 8 12:41:40 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "tcu70a5ibi8qjkfjn4eq3ddem1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.4_6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1478572607980" -context "sdk\\\\bsp/1478572607980"
webtalk_add_data -client sdk -key hwid -value "1469685061930" -context "sdk\\\\bsp/1478572607980"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1478572607980"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1478572607980"
webtalk_transmit -clientid 2125792874 -regid "" -xml D:\\SMartCart\\hdl_prj\\vivado_ip_prj\\vivado_prj.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html D:\\SMartCart\\hdl_prj\\vivado_ip_prj\\vivado_prj.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm D:\\SMartCart\\hdl_prj\\vivado_ip_prj\\vivado_prj.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
