-- -------------------------------------------------------------
-- 
-- File Name: D:\Matlab_Vhd\hdl_prj\hdlsrc\smartCart3111\head_ip_src_head.vhd
-- Created: 2016-07-17 11:16:19
-- 
-- Generated by MATLAB 9.0 and HDL Coder 3.8
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1
-- Target subsystem base rate: 1
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- (no clock)    0
-- ce_out        1
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- signals                       ce_out        1
-- I0_OUT                        (no clock)    1.#INF
-- strob                         ce_out        1
-- Out1                          ce_out        1
-- Out2                          ce_out        1
-- Out3                          ce_out        1
-- Out4                          ce_out        1
-- Out5                          ce_out        1
-- Out6                          ce_out        1
-- Out7                          ce_out        1
-- Out8                          ce_out        1
-- irq                           ce_out        1
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: head_ip_src_head
-- Source Path: smartCart3111/head
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY head_ip_src_head IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        comanda                           :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        IO                                :   IN    std_logic;
        data_in_1                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_2                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_3                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_4                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_5                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_6                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_7                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_8                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        ce_out                            :   OUT   std_logic;
        signals                           :   OUT   std_logic_vector(3 DOWNTO 0);  -- sfix4
        I0_OUT                            :   OUT   std_logic;
        strob                             :   OUT   std_logic;
        Out1                              :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        Out2                              :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        Out3                              :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        Out4                              :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        Out5                              :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        Out6                              :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        Out7                              :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        Out8                              :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        irq                               :   OUT   std_logic
        );
END head_ip_src_head;


ARCHITECTURE rtl OF head_ip_src_head IS

  -- Component Declarations
  COMPONENT head_ip_src_DEMUX
    PORT( COMMANDA                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          start                           :   OUT   std_logic;
          stop                            :   OUT   std_logic;
          RD_WR                           :   OUT   std_logic;
          STEP                            :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
          RST_IRQ                         :   OUT   std_logic;
          Number_write_byte               :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
          );
  END COMPONENT;

  COMPONENT head_ip_src_switch_io
    PORT( IO                              :   IN    std_logic;
          IO_IN                           :   IN    std_logic;
          switch_io                       :   IN    std_logic;
          Out1                            :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT head_ip_src_Interface
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          IO                              :   IN    std_logic;
          START                           :   IN    std_logic;
          STOP                            :   IN    std_logic;
          signals2                        :   OUT   std_logic_vector(3 DOWNTO 0);  -- sfix4
          Out3                            :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT head_ip_src_MUX
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          ADR1                            :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          ADR2                            :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          mADR3                           :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          Data1                           :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          Data2                           :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          mData3                          :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          DataOut                         :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          AdrOut                          :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
          );
  END COMPONENT;

  COMPONENT head_ip_src_Manager
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          AdrrIN                          :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          DataIN                          :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          Start                           :   IN    std_logic;
          Stop                            :   IN    std_logic;
          RD                              :   IN    std_logic;
          STEP                            :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          RST_IRQ                         :   IN    std_logic;
          data_in_1                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_2                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_3                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_4                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_5                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_6                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_7                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_8                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          addrout                         :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
          DATA_OUT                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          Out1                            :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
          Out2                            :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
          Out3                            :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
          Out4                            :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
          Out5                            :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
          Out6                            :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
          Out7                            :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
          Out8                            :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
          irq                             :   OUT   std_logic;
          addr_mux                        :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
          data_mux                        :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
          );
  END COMPONENT;

  COMPONENT head_ip_src_Reciver
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          enb_const_rate                  :   IN    std_logic;
          RST                             :   IN    std_logic_vector(3 DOWNTO 0);  -- sfix4
          IO                              :   IN    std_logic;
          STOP                            :   IN    std_logic;
          adr_IN                          :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          data_in                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          AddrOUT                         :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
          STATUS                          :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          Strob                           :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : head_ip_src_DEMUX
    USE ENTITY work.head_ip_src_DEMUX(rtl);

  FOR ALL : head_ip_src_switch_io
    USE ENTITY work.head_ip_src_switch_io(rtl);

  FOR ALL : head_ip_src_Interface
    USE ENTITY work.head_ip_src_Interface(rtl);

  FOR ALL : head_ip_src_MUX
    USE ENTITY work.head_ip_src_MUX(rtl);

  FOR ALL : head_ip_src_Manager
    USE ENTITY work.head_ip_src_Manager(rtl);

  FOR ALL : head_ip_src_Reciver
    USE ENTITY work.head_ip_src_Reciver(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL TmpGroundAtswitch_ioInport2_out1 : std_logic;
  SIGNAL comanda_unsigned                 : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay_out1                       : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL DEMUX_out1                       : std_logic;
  SIGNAL DEMUX_out2                       : std_logic;
  SIGNAL DEMUX_out3                       : std_logic;
  SIGNAL DEMUX_out4                       : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL DEMUX_out5                       : std_logic;
  SIGNAL DEMUX_out6                       : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL switch_io_out1                   : std_logic;
  SIGNAL Interface_out1                   : std_logic_vector(3 DOWNTO 0);  -- ufix4
  SIGNAL Interface_out2                   : std_logic;
  SIGNAL TmpGroundAtMUXInport2_out1       : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL TmpGroundAtMUXInport5_out1       : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Reciver_out1                     : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL Manager_out12                    : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL Reciver_out2                     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Manager_out13                    : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL MUX_out1                         : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL MUX_out2                         : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL Manager_out1                     : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL Manager_out2                     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Manager_out3                     : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL Manager_out4                     : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL Manager_out5                     : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL Manager_out6                     : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL Manager_out7                     : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL Manager_out8                     : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL Manager_out9                     : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL Manager_out10                    : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL Manager_out11                    : std_logic;
  SIGNAL Reciver_out3                     : std_logic;

BEGIN
  -- Переключатель адрес 4
  -- 
  -- Приёмник адрес (1)  
  -- 1-2 бит   тип сообщения  если  1 то соостояние счётчика  2 считыные байт байты
  -- 3-11 бит значение сяётчика адреса 
  -- 12-20 бит считанный байт 

  u_DEMUX : head_ip_src_DEMUX
    PORT MAP( COMMANDA => std_logic_vector(Delay_out1),  -- uint32
              start => DEMUX_out1,
              stop => DEMUX_out2,
              RD_WR => DEMUX_out3,
              STEP => DEMUX_out4,  -- uint8
              RST_IRQ => DEMUX_out5,
              Number_write_byte => DEMUX_out6  -- uint8
              );

  u_switch_io : head_ip_src_switch_io
    PORT MAP( IO => IO,
              IO_IN => TmpGroundAtswitch_ioInport2_out1,
              switch_io => DEMUX_out3,
              Out1 => switch_io_out1
              );

  u_Interface : head_ip_src_Interface
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              IO => switch_io_out1,
              START => DEMUX_out1,
              STOP => DEMUX_out2,
              signals2 => Interface_out1,  -- sfix4
              Out3 => Interface_out2
              );

  u_MUX : head_ip_src_MUX
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              ADR1 => Reciver_out1,  -- uint8
              ADR2 => std_logic_vector(TmpGroundAtMUXInport2_out1),  -- uint8
              mADR3 => Manager_out12,  -- uint8
              Data1 => Reciver_out2,  -- uint32
              Data2 => std_logic_vector(TmpGroundAtMUXInport5_out1),  -- uint32
              mData3 => Manager_out13,  -- uint32
              DataOut => MUX_out1,  -- uint32
              AdrOut => MUX_out2  -- uint8
              );

  u_Manager : head_ip_src_Manager
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              AdrrIN => MUX_out2,  -- uint8
              DataIN => MUX_out1,  -- uint32
              Start => DEMUX_out1,
              Stop => DEMUX_out2,
              RD => DEMUX_out3,
              STEP => DEMUX_out4,  -- uint8
              RST_IRQ => DEMUX_out5,
              data_in_1 => data_in_1,  -- uint32
              data_in_2 => data_in_2,  -- uint32
              data_in_3 => data_in_3,  -- uint32
              data_in_4 => data_in_4,  -- uint32
              data_in_5 => data_in_5,  -- uint32
              data_in_6 => data_in_6,  -- uint32
              data_in_7 => data_in_7,  -- uint32
              data_in_8 => data_in_8,  -- uint32
              addrout => Manager_out1,  -- uint8
              DATA_OUT => Manager_out2,  -- uint32
              Out1 => Manager_out3,  -- uint8
              Out2 => Manager_out4,  -- uint8
              Out3 => Manager_out5,  -- uint8
              Out4 => Manager_out6,  -- uint8
              Out5 => Manager_out7,  -- uint8
              Out6 => Manager_out8,  -- uint8
              Out7 => Manager_out9,  -- uint8
              Out8 => Manager_out10,  -- uint8
              irq => Manager_out11,
              addr_mux => Manager_out12,  -- uint8
              data_mux => Manager_out13  -- uint32
              );

  u_Reciver : head_ip_src_Reciver
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              enb_const_rate => clk_enable,
              RST => Interface_out1,  -- sfix4
              IO => switch_io_out1,
              STOP => DEMUX_out2,
              adr_IN => Manager_out1,  -- uint8
              data_in => Manager_out2,  -- uint32
              AddrOUT => Reciver_out1,  -- uint8
              STATUS => Reciver_out2,  -- uint32
              Strob => Reciver_out3
              );

  TmpGroundAtswitch_ioInport2_out1 <= '0';

  comanda_unsigned <= unsigned(comanda);

  enb <= clk_enable;

  Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay_out1 <= comanda_unsigned;
      END IF;
    END IF;
  END PROCESS Delay_process;


  TmpGroundAtMUXInport2_out1 <= to_unsigned(16#00#, 8);

  TmpGroundAtMUXInport5_out1 <= to_unsigned(0, 32);

  ce_out <= clk_enable;

  signals <= Interface_out1;

  I0_OUT <= Interface_out2;

  strob <= Reciver_out3;

  Out1 <= Manager_out3;

  Out2 <= Manager_out4;

  Out3 <= Manager_out5;

  Out4 <= Manager_out6;

  Out5 <= Manager_out7;

  Out6 <= Manager_out8;

  Out7 <= Manager_out9;

  Out8 <= Manager_out10;

  irq <= Manager_out11;

END rtl;

