vlib work
vcom  head_ip_src_ColdStart.vhd
vcom  head_ip_src_ColdStop2.vhd
vcom  head_ip_src_Head2.vhd
vcom  head_ip_src_MUX2.vhd
vcom  head_ip_src_Swith_signal2.vhd
vcom  head_ip_src_Interface.vhd
vcom  head_ip_src_SinglePortRAM_32x8b.vhd
vcom  head_ip_src_SinglePortRAM_Wrapper_32x8b.vhd
vcom  head_ip_src_Reciver.vhd
vcom  head_ip_src_head.vhd
