-- -------------------------------------------------------------
-- 
-- File Name: D:\direct_ip\smart_ip\hdlsrc\smartCart5_1work\head_ip_src_Manager.vhd
-- Created: 2017-11-07 14:24:49
-- 
-- Generated by MATLAB 9.0 and HDL Coder 3.8
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: head_ip_src_Manager
-- Source Path: smartCart5_1work/head/Manager
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.head_ip_src_head_pkg.ALL;

ENTITY head_ip_src_Manager IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        AdrrIN                            :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        DataIN                            :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        Start                             :   IN    std_logic;
        Stop                              :   IN    std_logic;
        RD                                :   IN    std_logic;
        STEP                              :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        RST_IRQ                           :   IN    std_logic;
        Number_write_byte                 :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        ON_TRANSMITE                      :   IN    std_logic;
        time_pause                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_0                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_1                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_2                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_3                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_4                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_5                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_6                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_7                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_8                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_9                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_10                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_11                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_12                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_13                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_14                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_15                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_16                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_17                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_18                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_19                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_20                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_21                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_22                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_23                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_24                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_25                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_26                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_27                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_28                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_29                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_30                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_31                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_32                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_33                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_34                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_35                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_36                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_37                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_38                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_39                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_40                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_41                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_42                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_43                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_44                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_45                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_46                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_47                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_48                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_49                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_50                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_51                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_52                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_53                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_54                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_55                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_56                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_57                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_58                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_59                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_60                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_61                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_62                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_63                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        addrout                           :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        DATA_OUT                          :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        Out1                              :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        Out2                              :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        Out3                              :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        Out4                              :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        Out5                              :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        Out6                              :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        Out7                              :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        Out8                              :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        irq                               :   OUT   std_logic;
        addr_mux                          :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        data_mux                          :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        STATUS                            :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        rd_switch                         :   OUT   std_logic
        );
END head_ip_src_Manager;


ARCHITECTURE rtl OF head_ip_src_Manager IS

  -- Component Declarations
  COMPONENT head_ip_src_signal_edg
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In1                             :   IN    std_logic;
          Out1                            :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT head_ip_src_Atomic_Subsystem
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          addr                            :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          rst                             :   IN    std_logic;
          data_in_1                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_2                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_3                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_4                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_5                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_6                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_7                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_8                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_9                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_10                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_11                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_12                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_13                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_14                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_15                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_16                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_17                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_18                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_19                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_20                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_21                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_22                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_23                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_24                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_25                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_26                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_27                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_28                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_29                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_30                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_31                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_32                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_33                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_34                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_35                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_36                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_37                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_38                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_39                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_40                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_41                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_42                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_43                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_44                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_45                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_46                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_47                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_48                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_49                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_50                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_51                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_52                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_53                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_54                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_55                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_56                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_57                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_58                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_59                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_60                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_61                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_62                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_63                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_64                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          DataOut                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : head_ip_src_signal_edg
    USE ENTITY work.head_ip_src_signal_edg(rtl);

  FOR ALL : head_ip_src_Atomic_Subsystem
    USE ENTITY work.head_ip_src_Atomic_Subsystem(rtl);

  -- Signals
  SIGNAL signal_edg7_out1                 : std_logic;
  SIGNAL signal_edg10_out1                : std_logic;
  SIGNAL HDL_Counter12_out1               : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Logical_Operator24_out1          : std_logic;
  SIGNAL Logical_Operator15_out1          : std_logic;
  SIGNAL HDL_Counter12_stepreg            : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Compare_To_Constant19_out1       : std_logic;
  SIGNAL Logical_Operator16_out1          : std_logic;
  SIGNAL Unit_Delay_Enabled_Resettable16_out1 : std_logic;
  SIGNAL Delay16_out1                     : std_logic;
  SIGNAL Unit_Delay_Enabled_Resettable16_switch_delay : std_logic;  -- ufix1
  SIGNAL signal_edg8_out1                 : std_logic;
  SIGNAL Constant35_out1                  : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Number_write_byte_unsigned       : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Switch17_out1                    : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Compare_To_Constant18_out1       : std_logic;
  SIGNAL signal_edg1_out1                 : std_logic;
  SIGNAL Delay9_out1                      : std_logic;
  SIGNAL Logical_Operator20_out1          : std_logic;
  SIGNAL Unit_Delay_Enabled_Resettable28_switch_delay : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL Unit_Delay_Enabled_Resettable28_out1 : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Unit_Delay_Enabled_Resettable28_out1_is_not0 : std_logic;
  SIGNAL Compare_To_Constant24_out1       : std_logic;
  SIGNAL signal_edg9_out1                 : std_logic;
  SIGNAL Constant36_out1                  : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Constant29_out1                  : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Switch18_out1                    : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Unit_Delay_Enabled_Resettable15_switch_delay : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL Unit_Delay_Enabled_Resettable15_out1 : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL AdrrIN_unsigned                  : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Compare_To_Constant13_out1       : std_logic;
  SIGNAL Delay13_out1                     : std_logic;
  SIGNAL Logical_Operator5_out1           : std_logic;
  SIGNAL Delay14_out1                     : std_logic;
  SIGNAL Logical_Operator4_out1           : std_logic;
  SIGNAL Compare_To_Constant1_out1        : std_logic;
  SIGNAL Delay1_out1                      : std_logic;
  SIGNAL Logical_Operator2_out1           : std_logic;
  SIGNAL Logical_Operator3_out1           : std_logic;
  SIGNAL DataIN_unsigned                  : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Constant40_out1                  : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL time_pause_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Switch21_out1                    : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL signal_edg12_out1                : std_logic;
  SIGNAL Logical_Operator13_out1          : std_logic;
  SIGNAL Unit_Delay_Enabled_Resettable2_switch_delay : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL Unit_Delay_Enabled_Resettable2_out1 : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Compare_To_Constant22_out1       : std_logic;
  SIGNAL Logical_Operator31_out1          : std_logic;
  SIGNAL HDL_Counter13_out1               : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Relational_Operator6_relop1      : std_logic;
  SIGNAL Logical_Operator27_out1          : std_logic;
  SIGNAL HDL_Counter9_out1                : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Relational_Operator8_relop1      : std_logic;
  SIGNAL Logical_Operator29_out1          : std_logic;
  SIGNAL Delay15_out1                     : std_logic;
  SIGNAL Logical_Operator28_out1          : std_logic;
  SIGNAL signal_edg2_out1                 : std_logic;
  SIGNAL signal_edg2_out1_1               : std_logic;
  SIGNAL Logical_Operator22_out1          : std_logic;
  SIGNAL Constant28_out1                  : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Constant27_out1                  : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Switch8_out1                     : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Constant23_out1                  : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Compare_To_Constant12_out1       : std_logic;
  SIGNAL Logical_Operator14_out1          : std_logic;
  SIGNAL Unit_Delay_Enabled_Resettable1_switch_delay : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL Unit_Delay_Enabled_Resettable1_out1 : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Bit_Slice3_out1                  : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL Compare_To_Constant10_out1       : std_logic;
  SIGNAL Constant15_out1                  : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Bit_Slice4_out1                  : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Switch10_out1                    : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL STEP_unsigned                    : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Relational_Operator_relop1       : std_logic;
  SIGNAL Logical_Operator19_out1          : std_logic;
  SIGNAL HDL_Counter5_out1                : std_logic;  -- ufix1
  SIGNAL Compare_To_Constant3_out1        : std_logic;
  SIGNAL Logical_Operator11_out1          : std_logic;
  SIGNAL Constant10_out1                  : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Add5_out1                        : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL Logical_Operator12_out1          : std_logic;
  SIGNAL HDL_Counter4_out1                : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL Relational_Operator4_relop1      : std_logic;
  SIGNAL Logical_Operator18_out1          : std_logic;
  SIGNAL Delay6_out1                      : std_logic;
  SIGNAL Logical_Operator17_out1          : std_logic;
  SIGNAL Logical_Operator8_out1           : std_logic;
  SIGNAL Constant9_out1                   : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Add_out1                         : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL Data_Type_Conversion6_out1       : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL Unit_Delay_Enabled_Resettable4_out1 : std_logic;
  SIGNAL HDL_Counter7_out1                : std_logic;  -- ufix1
  SIGNAL Compare_To_Constant5_out1        : std_logic;
  SIGNAL Relational_Operator2_relop1      : std_logic;
  SIGNAL Delay3_out1                      : std_logic;
  SIGNAL Logical_Operator10_out1          : std_logic;
  SIGNAL Logical_Operator9_out1           : std_logic;
  SIGNAL HDL_Counter2_out1                : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL Unit_Delay_Enabled_Resettable4_switch_delay : std_logic;  -- ufix1
  SIGNAL Constant2_out1                   : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Constant1_out1                   : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Switch1_out1                     : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Switch13_out1                    : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Add1_out1                        : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL Data_Type_Conversion4_out1       : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Delay8_out1                      : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Constant34_out1                  : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Constant17_out1                  : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Compare_To_Constant23_out1       : std_logic;
  SIGNAL Constant13_out1                  : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Switch4_out1                     : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Delay12_out1                     : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Atomic_Subsystem_out1            : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Atomic_Subsystem_out1_unsigned   : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Switch6_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Data_Type_Conversion3_out1       : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Constant26_out1                  : std_logic;
  SIGNAL Constant21_out1                  : std_logic;
  SIGNAL Constant20_out1                  : std_logic;
  SIGNAL Bit_Concat3_out1                 : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL Constant19_out1                  : std_logic;
  SIGNAL Constant18_out1                  : std_logic;
  SIGNAL Constant16_out1                  : std_logic;
  SIGNAL Bit_Concat2_out1                 : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL Switch7_out1                     : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL Bit_Concat4_out1                 : unsigned(10 DOWNTO 0);  -- ufix11
  SIGNAL Bit_Concat4_out1_dtc             : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Switch16_out1                    : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Constant22_out1                  : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Constant24_out1                  : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Add3_out1                        : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL Data_Type_Conversion9_out1       : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL Unit_Delay_Enabled_Resettable3_out1 : std_logic;
  SIGNAL HDL_Counter6_out1                : std_logic;  -- ufix1
  SIGNAL Compare_To_Constant4_out1        : std_logic;
  SIGNAL Relational_Operator1_relop1      : std_logic;
  SIGNAL Delay2_out1                      : std_logic;
  SIGNAL Logical_Operator7_out1           : std_logic;
  SIGNAL Logical_Operator6_out1           : std_logic;
  SIGNAL HDL_Counter1_out1                : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL Unit_Delay_Enabled_Resettable3_switch_delay : std_logic;  -- ufix1
  SIGNAL Constant_out1                    : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Constant_out1_dtc                : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL Data_Type_Conversion_out1        : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Constant5_out1                   : std_logic;
  SIGNAL Bit_Concat1_out1                 : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL Constant25_out1                  : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Constant3_out1                   : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Switch14_out1                    : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Constant4_out1                   : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Switch2_out1                     : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL Switch3_out1                     : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Data_Type_Conversion10_out1      : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL Bit_Concat_out1                  : unsigned(10 DOWNTO 0);  -- ufix11
  SIGNAL Data_Type_Conversion1_out1       : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Switch12_out1                    : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Add2_out1                        : unsigned(32 DOWNTO 0);  -- ufix33
  SIGNAL Data_Type_Conversion5_out1       : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay7_out1                      : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Constant7_out1                   : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Add4_out1                        : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL Compare_To_Constant9_out1        : std_logic;
  SIGNAL signal_edg_out1                  : std_logic;
  SIGNAL Relational_Operator3_relop1      : std_logic;
  SIGNAL Unit_Delay_Enabled_Resettable5_switch_delay : std_logic;  -- ufix1
  SIGNAL Unit_Delay_Enabled_Resettable5_out1 : std_logic;
  SIGNAL HDL_Counter8_out1                : std_logic;  -- ufix1
  SIGNAL Compare_To_Constant2_out1        : std_logic;
  SIGNAL HDL_Counter3_out1                : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Compare_To_Constant6_out1        : std_logic;
  SIGNAL Constant14_out1                  : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Bit_Slice5_out1                  : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Switch9_out1                     : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Delay4_reg                       : vector_of_unsigned8(0 TO 2);  -- ufix8 [3]
  SIGNAL Delay4_out1                      : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Unit_Delay_Enabled_Resettable6_switch_delay : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL Unit_Delay_Enabled_Resettable6_out1 : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Compare_To_Constant7_out1        : std_logic;
  SIGNAL Unit_Delay_Enabled_Resettable7_switch_delay : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL Unit_Delay_Enabled_Resettable7_out1 : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Compare_To_Constant8_out1        : std_logic;
  SIGNAL Unit_Delay_Enabled_Resettable8_switch_delay : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL Unit_Delay_Enabled_Resettable8_out1 : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Compare_To_Constant11_out1       : std_logic;
  SIGNAL Unit_Delay_Enabled_Resettable9_switch_delay : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL Unit_Delay_Enabled_Resettable9_out1 : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Compare_To_Constant14_out1       : std_logic;
  SIGNAL Unit_Delay_Enabled_Resettable10_switch_delay : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL Unit_Delay_Enabled_Resettable10_out1 : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Compare_To_Constant15_out1       : std_logic;
  SIGNAL Unit_Delay_Enabled_Resettable11_switch_delay : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL Unit_Delay_Enabled_Resettable11_out1 : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Compare_To_Constant16_out1       : std_logic;
  SIGNAL Unit_Delay_Enabled_Resettable12_switch_delay : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL Unit_Delay_Enabled_Resettable12_out1 : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Compare_To_Constant17_out1       : std_logic;
  SIGNAL Unit_Delay_Enabled_Resettable13_switch_delay : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL Unit_Delay_Enabled_Resettable13_out1 : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL signal_edg4_out1                 : std_logic;
  SIGNAL Delay5_out1                      : std_logic;
  SIGNAL Constant12_out1                  : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Add7_out1                        : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL Logical_Operator26_out1          : std_logic;
  SIGNAL signal_edg3_out1                 : std_logic;
  SIGNAL HDL_Counter10_out1               : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Relational_Operator7_relop1      : std_logic;
  SIGNAL Compare_To_Constant25_out1       : std_logic;
  SIGNAL signal_edg11_out1                : std_logic;
  SIGNAL Delay17_out1                     : std_logic;
  SIGNAL Logical_Operator30_out1          : std_logic;
  SIGNAL Unit_Delay_Enabled_Resettable25_switch_delay : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL Unit_Delay_Enabled_Resettable25_out1 : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Compare_To_Constant26_out1       : std_logic;
  SIGNAL Logical_Operator23_out1          : std_logic;
  SIGNAL Unit_Delay_Enabled_Resettable14_switch_delay : std_logic;  -- ufix1
  SIGNAL Unit_Delay_Enabled_Resettable14_out1 : std_logic;
  SIGNAL Constant11_out1                  : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Constant8_out1                   : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Constant6_out1                   : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Switch5_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Constant31_out1                  : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Constant30_out1                  : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Switch11_out1                    : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Constant33_out1                  : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Constant32_out1                  : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Switch15_out1                    : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Constant38_out1                  : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Constant37_out1                  : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Switch19_out1                    : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Add6_add_temp                    : unsigned(33 DOWNTO 0);  -- ufix34
  SIGNAL Add6_out1                        : unsigned(33 DOWNTO 0);  -- ufix34
  SIGNAL Data_Type_Conversion12_out1      : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Unit_Delay_Enabled_Resettable26_switch_delay : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL Unit_Delay_Enabled_Resettable26_out1 : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Logical_Operator25_out1          : std_logic;
  SIGNAL Logical_Operator32_out1          : std_logic;

BEGIN
  -- Декодер команд
  -- 
  -- Схема декодирования команд 
  -- 
  -- Схема синхр
  -- 
  -- Схема включения и выключения
  -- 
  -- Схема  управления приёмника
  -- 
  -- Схема управления передатчиком 

  u_signal_edg7 : head_ip_src_signal_edg
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              In1 => ON_TRANSMITE,
              Out1 => signal_edg7_out1
              );

  u_signal_edg10 : head_ip_src_signal_edg
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              In1 => RST_IRQ,
              Out1 => signal_edg10_out1
              );

  u_signal_edg8 : head_ip_src_signal_edg
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              In1 => Unit_Delay_Enabled_Resettable16_out1,
              Out1 => signal_edg8_out1
              );

  u_signal_edg1 : head_ip_src_signal_edg
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              In1 => Compare_To_Constant18_out1,
              Out1 => signal_edg1_out1
              );

  u_signal_edg9 : head_ip_src_signal_edg
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              In1 => Compare_To_Constant24_out1,
              Out1 => signal_edg9_out1
              );

  u_signal_edg12 : head_ip_src_signal_edg
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              In1 => Relational_Operator6_relop1,
              Out1 => signal_edg12_out1
              );

  u_signal_edg2 : head_ip_src_signal_edg
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              In1 => Logical_Operator28_out1,
              Out1 => signal_edg2_out1
              );

  u_Atomic_Subsystem : head_ip_src_Atomic_Subsystem
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              addr => std_logic_vector(Delay12_out1),  -- uint8
              rst => Logical_Operator3_out1,
              data_in_1 => data_in_0,  -- uint32
              data_in_2 => data_in_1,  -- uint32
              data_in_3 => data_in_2,  -- uint32
              data_in_4 => data_in_3,  -- uint32
              data_in_5 => data_in_4,  -- uint32
              data_in_6 => data_in_5,  -- uint32
              data_in_7 => data_in_6,  -- uint32
              data_in_8 => data_in_7,  -- uint32
              data_in_9 => data_in_8,  -- uint32
              data_in_10 => data_in_9,  -- uint32
              data_in_11 => data_in_10,  -- uint32
              data_in_12 => data_in_11,  -- uint32
              data_in_13 => data_in_12,  -- uint32
              data_in_14 => data_in_13,  -- uint32
              data_in_15 => data_in_14,  -- uint32
              data_in_16 => data_in_15,  -- uint32
              data_in_17 => data_in_16,  -- uint32
              data_in_18 => data_in_17,  -- uint32
              data_in_19 => data_in_18,  -- uint32
              data_in_20 => data_in_19,  -- uint32
              data_in_21 => data_in_20,  -- uint32
              data_in_22 => data_in_21,  -- uint32
              data_in_23 => data_in_22,  -- uint32
              data_in_24 => data_in_23,  -- uint32
              data_in_25 => data_in_24,  -- uint32
              data_in_26 => data_in_25,  -- uint32
              data_in_27 => data_in_26,  -- uint32
              data_in_28 => data_in_27,  -- uint32
              data_in_29 => data_in_28,  -- uint32
              data_in_30 => data_in_29,  -- uint32
              data_in_31 => data_in_30,  -- uint32
              data_in_32 => data_in_31,  -- uint32
              data_in_33 => data_in_32,  -- uint32
              data_in_34 => data_in_33,  -- uint32
              data_in_35 => data_in_34,  -- uint32
              data_in_36 => data_in_35,  -- uint32
              data_in_37 => data_in_36,  -- uint32
              data_in_38 => data_in_37,  -- uint32
              data_in_39 => data_in_38,  -- uint32
              data_in_40 => data_in_39,  -- uint32
              data_in_41 => data_in_40,  -- uint32
              data_in_42 => data_in_41,  -- uint32
              data_in_43 => data_in_42,  -- uint32
              data_in_44 => data_in_43,  -- uint32
              data_in_45 => data_in_44,  -- uint32
              data_in_46 => data_in_45,  -- uint32
              data_in_47 => data_in_46,  -- uint32
              data_in_48 => data_in_47,  -- uint32
              data_in_49 => data_in_48,  -- uint32
              data_in_50 => data_in_49,  -- uint32
              data_in_51 => data_in_50,  -- uint32
              data_in_52 => data_in_51,  -- uint32
              data_in_53 => data_in_52,  -- uint32
              data_in_54 => data_in_53,  -- uint32
              data_in_55 => data_in_54,  -- uint32
              data_in_56 => data_in_55,  -- uint32
              data_in_57 => data_in_56,  -- uint32
              data_in_58 => data_in_57,  -- uint32
              data_in_59 => data_in_58,  -- uint32
              data_in_60 => data_in_59,  -- uint32
              data_in_61 => data_in_60,  -- uint32
              data_in_62 => data_in_61,  -- uint32
              data_in_63 => data_in_62,  -- uint32
              data_in_64 => data_in_63,  -- uint32
              DataOut => Atomic_Subsystem_out1  -- uint32
              );

  u_signal_edg : head_ip_src_signal_edg
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              In1 => Compare_To_Constant9_out1,
              Out1 => signal_edg_out1
              );

  u_signal_edg4 : head_ip_src_signal_edg
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              In1 => Relational_Operator3_relop1,
              Out1 => signal_edg4_out1
              );

  u_signal_edg3 : head_ip_src_signal_edg
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              In1 => Logical_Operator26_out1,
              Out1 => signal_edg3_out1
              );

  u_signal_edg11 : head_ip_src_signal_edg
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              In1 => Compare_To_Constant26_out1,
              Out1 => signal_edg11_out1
              );

  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 100
  HDL_Counter12_step_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      HDL_Counter12_stepreg <= to_unsigned(16#01#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Logical_Operator24_out1 = '1' THEN 
          HDL_Counter12_stepreg <= to_unsigned(16#01#, 8);
        ELSIF Logical_Operator15_out1 = '1' THEN 
          IF HDL_Counter12_out1 = to_unsigned(16#63#, 8) THEN 
            HDL_Counter12_stepreg <= to_unsigned(16#9C#, 8);
          ELSE 
            HDL_Counter12_stepreg <= to_unsigned(16#01#, 8);
          END IF;
        END IF;
      END IF;
    END IF;
  END PROCESS HDL_Counter12_step_process;


  Logical_Operator16_out1 <=  NOT Compare_To_Constant19_out1;

  Delay16_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay16_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay16_out1 <= Unit_Delay_Enabled_Resettable16_out1;
      END IF;
    END IF;
  END PROCESS Delay16_process;


  Logical_Operator15_out1 <= Delay16_out1 AND Logical_Operator16_out1;

  Unit_Delay_Enabled_Resettable16_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Resettable16_switch_delay <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Compare_To_Constant19_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable16_switch_delay <= '0';
        ELSIF signal_edg7_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable16_switch_delay <= signal_edg7_out1;
        END IF;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Resettable16_process;

  
  Unit_Delay_Enabled_Resettable16_out1 <= '0' WHEN Compare_To_Constant19_out1 = '1' ELSE
      Unit_Delay_Enabled_Resettable16_switch_delay;

  Logical_Operator24_out1 <= signal_edg8_out1 OR signal_edg10_out1;

  HDL_Counter12_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      HDL_Counter12_out1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Logical_Operator24_out1 = '1' THEN 
          HDL_Counter12_out1 <= to_unsigned(16#00#, 8);
        ELSIF Logical_Operator15_out1 = '1' THEN 
          HDL_Counter12_out1 <= HDL_Counter12_out1 + HDL_Counter12_stepreg;
        END IF;
      END IF;
    END IF;
  END PROCESS HDL_Counter12_process;


  
  Compare_To_Constant19_out1 <= '1' WHEN HDL_Counter12_out1 = to_unsigned(16#64#, 8) ELSE
      '0';

  Constant35_out1 <= to_unsigned(16#FF#, 8);

  Number_write_byte_unsigned <= unsigned(Number_write_byte);

  
  Switch17_out1 <= Constant35_out1 WHEN Compare_To_Constant19_out1 = '0' ELSE
      Number_write_byte_unsigned;

  
  Compare_To_Constant18_out1 <= '1' WHEN Switch17_out1 /= to_unsigned(16#FF#, 8) ELSE
      '0';

  Delay9_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay9_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay9_out1 <= signal_edg1_out1;
      END IF;
    END IF;
  END PROCESS Delay9_process;


  Logical_Operator20_out1 <= signal_edg1_out1 OR signal_edg10_out1;

  Unit_Delay_Enabled_Resettable28_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Resettable28_switch_delay <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Logical_Operator20_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable28_switch_delay <= to_unsigned(16#00#, 8);
        ELSIF Delay9_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable28_switch_delay <= Switch17_out1;
        END IF;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Resettable28_process;

  
  Unit_Delay_Enabled_Resettable28_out1 <= to_unsigned(16#00#, 8) WHEN Logical_Operator20_out1 = '1' ELSE
      Unit_Delay_Enabled_Resettable28_switch_delay;

  
  Unit_Delay_Enabled_Resettable28_out1_is_not0 <= '1' WHEN Unit_Delay_Enabled_Resettable28_out1 /= to_unsigned(16#00#, 8) ELSE
      '0';

  
  Compare_To_Constant24_out1 <= '1' WHEN Switch17_out1 = to_unsigned(16#00#, 8) ELSE
      '0';

  Constant36_out1 <= to_unsigned(16#00#, 8);

  Constant29_out1 <= to_unsigned(16#FF#, 8);

  
  Switch18_out1 <= Constant36_out1 WHEN signal_edg9_out1 = '0' ELSE
      Constant29_out1;

  Unit_Delay_Enabled_Resettable15_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Resettable15_switch_delay <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Logical_Operator20_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable15_switch_delay <= to_unsigned(16#00#, 8);
        ELSIF Delay9_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable15_switch_delay <= Switch17_out1;
        END IF;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Resettable15_process;

  
  Unit_Delay_Enabled_Resettable15_out1 <= to_unsigned(16#00#, 8) WHEN Logical_Operator20_out1 = '1' ELSE
      Unit_Delay_Enabled_Resettable15_switch_delay;

  AdrrIN_unsigned <= unsigned(AdrrIN);

  
  Compare_To_Constant13_out1 <= '1' WHEN AdrrIN_unsigned = to_unsigned(16#02#, 8) ELSE
      '0';

  Delay13_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay13_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay13_out1 <= Start;
      END IF;
    END IF;
  END PROCESS Delay13_process;


  Logical_Operator5_out1 <=  NOT Delay13_out1;

  Delay14_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay14_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay14_out1 <= Stop;
      END IF;
    END IF;
  END PROCESS Delay14_process;


  Logical_Operator4_out1 <= Logical_Operator5_out1 AND Delay14_out1;

  
  Compare_To_Constant1_out1 <= '1' WHEN Logical_Operator4_out1 = '1' ELSE
      '0';

  Delay1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay1_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay1_out1 <= Compare_To_Constant1_out1;
      END IF;
    END IF;
  END PROCESS Delay1_process;


  Logical_Operator2_out1 <= Delay1_out1 XOR Compare_To_Constant1_out1;

  Logical_Operator3_out1 <= Logical_Operator2_out1 AND Compare_To_Constant1_out1;

  DataIN_unsigned <= unsigned(DataIN);

  Constant40_out1 <= to_unsigned(1, 32);

  time_pause_unsigned <= unsigned(time_pause);

  
  Switch21_out1 <= Constant40_out1 WHEN Compare_To_Constant19_out1 = '0' ELSE
      time_pause_unsigned;

  Logical_Operator13_out1 <= Logical_Operator3_out1 OR signal_edg12_out1;

  Unit_Delay_Enabled_Resettable2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Resettable2_switch_delay <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Logical_Operator13_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable2_switch_delay <= to_unsigned(0, 32);
        ELSIF Compare_To_Constant13_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable2_switch_delay <= DataIN_unsigned;
        END IF;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Resettable2_process;

  
  Unit_Delay_Enabled_Resettable2_out1 <= to_unsigned(0, 32) WHEN Logical_Operator13_out1 = '1' ELSE
      Unit_Delay_Enabled_Resettable2_switch_delay;

  
  Compare_To_Constant22_out1 <= '1' WHEN Unit_Delay_Enabled_Resettable2_out1 = to_unsigned(1, 32) ELSE
      '0';

  Logical_Operator31_out1 <=  NOT Compare_To_Constant22_out1;

  -- Free running, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  HDL_Counter13_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      HDL_Counter13_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Logical_Operator31_out1 = '1' THEN 
          HDL_Counter13_out1 <= to_unsigned(0, 32);
        ELSIF Compare_To_Constant22_out1 = '1' THEN 
          HDL_Counter13_out1 <= HDL_Counter13_out1 + to_unsigned(1, 32);
        END IF;
      END IF;
    END IF;
  END PROCESS HDL_Counter13_process;


  
  Relational_Operator6_relop1 <= '1' WHEN HDL_Counter13_out1 = Switch21_out1 ELSE
      '0';

  -- Free running, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  HDL_Counter9_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      HDL_Counter9_out1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Logical_Operator20_out1 = '1' THEN 
          HDL_Counter9_out1 <= to_unsigned(16#00#, 8);
        ELSIF signal_edg9_out1 = '1' THEN 
          HDL_Counter9_out1 <= Switch18_out1;
        ELSIF Logical_Operator27_out1 = '1' THEN 
          HDL_Counter9_out1 <= HDL_Counter9_out1 + to_unsigned(16#01#, 8);
        END IF;
      END IF;
    END IF;
  END PROCESS HDL_Counter9_process;


  
  Relational_Operator8_relop1 <= '1' WHEN HDL_Counter9_out1 = Unit_Delay_Enabled_Resettable15_out1 ELSE
      '0';

  Logical_Operator29_out1 <=  NOT Relational_Operator8_relop1;

  Logical_Operator27_out1 <= signal_edg12_out1 AND (Unit_Delay_Enabled_Resettable28_out1_is_not0 AND Logical_Operator29_out1);

  Delay15_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay15_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay15_out1 <= Logical_Operator27_out1;
      END IF;
    END IF;
  END PROCESS Delay15_process;


  Logical_Operator28_out1 <= Delay9_out1 OR Delay15_out1;

  reduced_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      signal_edg2_out1_1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        signal_edg2_out1_1 <= signal_edg2_out1;
      END IF;
    END IF;
  END PROCESS reduced_process;


  Logical_Operator22_out1 <= signal_edg2_out1_1 OR signal_edg2_out1;

  Constant28_out1 <= to_unsigned(16#00#, 8);

  Constant27_out1 <= to_unsigned(16#02#, 8);

  
  Switch8_out1 <= Constant28_out1 WHEN Logical_Operator22_out1 = '0' ELSE
      Constant27_out1;

  Constant23_out1 <= to_unsigned(16#00#, 8);

  
  Compare_To_Constant12_out1 <= '1' WHEN AdrrIN_unsigned = to_unsigned(16#01#, 8) ELSE
      '0';

  Logical_Operator14_out1 <= Logical_Operator3_out1 OR Compare_To_Constant13_out1;

  Unit_Delay_Enabled_Resettable1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Resettable1_switch_delay <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Logical_Operator14_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable1_switch_delay <= to_unsigned(0, 32);
        ELSIF Compare_To_Constant12_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable1_switch_delay <= DataIN_unsigned;
        END IF;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Resettable1_process;

  
  Unit_Delay_Enabled_Resettable1_out1 <= to_unsigned(0, 32) WHEN Logical_Operator14_out1 = '1' ELSE
      Unit_Delay_Enabled_Resettable1_switch_delay;

  Bit_Slice3_out1 <= Unit_Delay_Enabled_Resettable1_out1(1 DOWNTO 0);

  
  Compare_To_Constant10_out1 <= '1' WHEN Bit_Slice3_out1 = to_unsigned(16#1#, 2) ELSE
      '0';

  Constant15_out1 <= to_unsigned(16#00#, 8);

  Bit_Slice4_out1 <= Unit_Delay_Enabled_Resettable1_out1(9 DOWNTO 2);

  
  Switch10_out1 <= Constant15_out1 WHEN Compare_To_Constant10_out1 = '0' ELSE
      Bit_Slice4_out1;

  STEP_unsigned <= unsigned(STEP);

  
  Relational_Operator_relop1 <= '1' WHEN Switch10_out1 = STEP_unsigned ELSE
      '0';

  Logical_Operator19_out1 <= Compare_To_Constant10_out1 AND Relational_Operator_relop1;

  -- Free running, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  HDL_Counter5_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      HDL_Counter5_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND Logical_Operator19_out1 = '1' THEN
        HDL_Counter5_out1 <=  NOT HDL_Counter5_out1;
      END IF;
    END IF;
  END PROCESS HDL_Counter5_process;


  
  Compare_To_Constant3_out1 <= '1' WHEN HDL_Counter5_out1 = '1' ELSE
      '0';

  Logical_Operator11_out1 <=  NOT Compare_To_Constant3_out1;

  Constant10_out1 <= to_unsigned(16#01#, 8);

  Add5_out1 <= resize(Constant10_out1, 9) + resize(STEP_unsigned, 9);

  -- Free running, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  HDL_Counter4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      HDL_Counter4_out1 <= to_unsigned(16#0#, 4);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Logical_Operator11_out1 = '1' THEN 
          HDL_Counter4_out1 <= to_unsigned(16#0#, 4);
        ELSIF Logical_Operator12_out1 = '1' THEN 
          HDL_Counter4_out1 <= HDL_Counter4_out1 + to_unsigned(16#1#, 4);
        END IF;
      END IF;
    END IF;
  END PROCESS HDL_Counter4_process;


  
  Relational_Operator4_relop1 <= '1' WHEN resize(HDL_Counter4_out1, 9) = Add5_out1 ELSE
      '0';

  Logical_Operator18_out1 <=  NOT Relational_Operator4_relop1;

  Logical_Operator12_out1 <= Compare_To_Constant3_out1 AND Logical_Operator18_out1;

  Delay6_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay6_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay6_out1 <= Logical_Operator12_out1;
      END IF;
    END IF;
  END PROCESS Delay6_process;


  Logical_Operator17_out1 <= Relational_Operator_relop1 AND Delay6_out1;

  Logical_Operator8_out1 <= Logical_Operator17_out1 AND Delay6_out1;

  Constant9_out1 <= to_unsigned(16#02#, 8);

  Add_out1 <= resize(Constant9_out1, 9) + resize(STEP_unsigned, 9);

  Data_Type_Conversion6_out1 <= Add_out1(3 DOWNTO 0);

  -- Free running, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  HDL_Counter7_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      HDL_Counter7_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND Unit_Delay_Enabled_Resettable4_out1 = '1' THEN
        HDL_Counter7_out1 <=  NOT HDL_Counter7_out1;
      END IF;
    END IF;
  END PROCESS HDL_Counter7_process;


  
  Compare_To_Constant5_out1 <= '1' WHEN HDL_Counter7_out1 = '1' ELSE
      '0';

  Delay3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay3_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay3_out1 <= Relational_Operator2_relop1;
      END IF;
    END IF;
  END PROCESS Delay3_process;


  Logical_Operator10_out1 <= Delay3_out1 XOR Relational_Operator2_relop1;

  Logical_Operator9_out1 <= Relational_Operator2_relop1 AND Logical_Operator10_out1;

  -- Free running, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  HDL_Counter2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      HDL_Counter2_out1 <= to_unsigned(16#0#, 4);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Logical_Operator9_out1 = '1' THEN 
          HDL_Counter2_out1 <= to_unsigned(16#0#, 4);
        ELSIF Compare_To_Constant5_out1 = '1' THEN 
          HDL_Counter2_out1 <= HDL_Counter2_out1 + to_unsigned(16#1#, 4);
        END IF;
      END IF;
    END IF;
  END PROCESS HDL_Counter2_process;


  
  Relational_Operator2_relop1 <= '1' WHEN HDL_Counter2_out1 = Data_Type_Conversion6_out1 ELSE
      '0';

  Unit_Delay_Enabled_Resettable4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Resettable4_switch_delay <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Relational_Operator2_relop1 = '1' THEN
          Unit_Delay_Enabled_Resettable4_switch_delay <= '0';
        ELSIF Logical_Operator8_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable4_switch_delay <= Logical_Operator8_out1;
        END IF;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Resettable4_process;

  
  Unit_Delay_Enabled_Resettable4_out1 <= '0' WHEN Relational_Operator2_relop1 = '1' ELSE
      Unit_Delay_Enabled_Resettable4_switch_delay;

  Constant2_out1 <= to_unsigned(16#00#, 8);

  Constant1_out1 <= to_unsigned(16#01#, 8);

  
  Switch1_out1 <= Constant2_out1 WHEN Unit_Delay_Enabled_Resettable4_out1 = '0' ELSE
      Constant1_out1;

  
  Switch13_out1 <= Constant23_out1 WHEN RD = '0' ELSE
      Switch1_out1;

  Add1_out1 <= resize(Switch8_out1, 9) + resize(Switch13_out1, 9);

  Data_Type_Conversion4_out1 <= Add1_out1(7 DOWNTO 0);

  Delay8_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay8_out1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay8_out1 <= Data_Type_Conversion4_out1;
      END IF;
    END IF;
  END PROCESS Delay8_process;


  addrout <= std_logic_vector(Delay8_out1);

  Constant34_out1 <= to_unsigned(0, 32);

  Constant17_out1 <= to_unsigned(0, 32);

  
  Compare_To_Constant23_out1 <= '1' WHEN HDL_Counter9_out1 = to_unsigned(16#FF#, 8) ELSE
      '0';

  Constant13_out1 <= to_unsigned(16#00#, 8);

  
  Switch4_out1 <= HDL_Counter9_out1 WHEN Compare_To_Constant23_out1 = '0' ELSE
      Constant13_out1;

  Delay12_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay12_out1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay12_out1 <= Switch4_out1;
      END IF;
    END IF;
  END PROCESS Delay12_process;


  Atomic_Subsystem_out1_unsigned <= unsigned(Atomic_Subsystem_out1);

  
  Switch6_out1 <= Constant17_out1 WHEN signal_edg2_out1_1 = '0' ELSE
      Atomic_Subsystem_out1_unsigned;

  Data_Type_Conversion3_out1 <= Switch6_out1(7 DOWNTO 0);

  Constant26_out1 <= '1';

  Constant21_out1 <= '0';

  Constant20_out1 <= '0';

  Bit_Concat3_out1 <= unsigned'(Constant26_out1 & Constant21_out1 & Constant20_out1);

  Constant19_out1 <= '0';

  Constant18_out1 <= '1';

  Constant16_out1 <= '1';

  Bit_Concat2_out1 <= unsigned'(Constant19_out1 & Constant18_out1 & Constant16_out1);

  
  Switch7_out1 <= Bit_Concat3_out1 WHEN signal_edg2_out1_1 = '0' ELSE
      Bit_Concat2_out1;

  Bit_Concat4_out1 <= Data_Type_Conversion3_out1 & Switch7_out1;

  Bit_Concat4_out1_dtc <= resize(Bit_Concat4_out1, 32);

  
  Switch16_out1 <= Constant34_out1 WHEN Logical_Operator22_out1 = '0' ELSE
      Bit_Concat4_out1_dtc;

  Constant22_out1 <= to_unsigned(0, 32);

  Constant24_out1 <= to_unsigned(16#01#, 8);

  Add3_out1 <= resize(Constant24_out1, 9) + resize(STEP_unsigned, 9);

  Data_Type_Conversion9_out1 <= Add3_out1(3 DOWNTO 0);

  -- Free running, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  HDL_Counter6_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      HDL_Counter6_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND Unit_Delay_Enabled_Resettable3_out1 = '1' THEN
        HDL_Counter6_out1 <=  NOT HDL_Counter6_out1;
      END IF;
    END IF;
  END PROCESS HDL_Counter6_process;


  
  Compare_To_Constant4_out1 <= '1' WHEN HDL_Counter6_out1 = '1' ELSE
      '0';

  Delay2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay2_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay2_out1 <= Relational_Operator1_relop1;
      END IF;
    END IF;
  END PROCESS Delay2_process;


  Logical_Operator7_out1 <= Delay2_out1 XOR Relational_Operator1_relop1;

  Logical_Operator6_out1 <= Relational_Operator1_relop1 AND Logical_Operator7_out1;

  -- Free running, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  HDL_Counter1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      HDL_Counter1_out1 <= to_unsigned(16#0#, 4);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Logical_Operator6_out1 = '1' THEN 
          HDL_Counter1_out1 <= to_unsigned(16#0#, 4);
        ELSIF Compare_To_Constant4_out1 = '1' THEN 
          HDL_Counter1_out1 <= HDL_Counter1_out1 + to_unsigned(16#1#, 4);
        END IF;
      END IF;
    END IF;
  END PROCESS HDL_Counter1_process;


  
  Relational_Operator1_relop1 <= '1' WHEN HDL_Counter1_out1 = Data_Type_Conversion9_out1 ELSE
      '0';

  Unit_Delay_Enabled_Resettable3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Resettable3_switch_delay <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Relational_Operator1_relop1 = '1' THEN
          Unit_Delay_Enabled_Resettable3_switch_delay <= '0';
        ELSIF Logical_Operator8_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable3_switch_delay <= Logical_Operator8_out1;
        END IF;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Resettable3_process;

  
  Unit_Delay_Enabled_Resettable3_out1 <= '0' WHEN Relational_Operator1_relop1 = '1' ELSE
      Unit_Delay_Enabled_Resettable3_switch_delay;

  Constant_out1 <= to_unsigned(16#00#, 8);

  Constant_out1_dtc <= resize(Constant_out1, 9);

  Data_Type_Conversion_out1 <= resize(HDL_Counter1_out1, 8);

  Constant5_out1 <= '1';

  Bit_Concat1_out1 <= Data_Type_Conversion_out1 & Constant5_out1;

  Constant25_out1 <= to_unsigned(16#00#, 8);

  Constant3_out1 <= to_unsigned(16#01#, 8);

  
  Switch14_out1 <= Constant25_out1 WHEN Unit_Delay_Enabled_Resettable4_out1 = '0' ELSE
      Constant3_out1;

  Constant4_out1 <= to_unsigned(16#02#, 8);

  
  Switch2_out1 <= Constant_out1_dtc WHEN Unit_Delay_Enabled_Resettable3_out1 = '0' ELSE
      Bit_Concat1_out1;

  
  Switch3_out1 <= Switch14_out1 WHEN Unit_Delay_Enabled_Resettable3_out1 = '0' ELSE
      Constant4_out1;

  Data_Type_Conversion10_out1 <= Switch3_out1(1 DOWNTO 0);

  Bit_Concat_out1 <= Switch2_out1 & Data_Type_Conversion10_out1;

  Data_Type_Conversion1_out1 <= resize(Bit_Concat_out1, 32);

  
  Switch12_out1 <= Constant22_out1 WHEN RD = '0' ELSE
      Data_Type_Conversion1_out1;

  Add2_out1 <= resize(Switch16_out1, 33) + resize(Switch12_out1, 33);

  Data_Type_Conversion5_out1 <= Add2_out1(31 DOWNTO 0);

  Delay7_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay7_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay7_out1 <= Data_Type_Conversion5_out1;
      END IF;
    END IF;
  END PROCESS Delay7_process;


  DATA_OUT <= std_logic_vector(Delay7_out1);

  Constant7_out1 <= to_unsigned(16#01#, 8);

  Add4_out1 <= resize(Constant7_out1, 9) + resize(STEP_unsigned, 9);

  
  Compare_To_Constant9_out1 <= '1' WHEN Bit_Slice3_out1 = to_unsigned(16#2#, 2) ELSE
      '0';

  Unit_Delay_Enabled_Resettable5_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Resettable5_switch_delay <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Relational_Operator3_relop1 = '1' THEN
          Unit_Delay_Enabled_Resettable5_switch_delay <= '0';
        ELSIF signal_edg_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable5_switch_delay <= signal_edg_out1;
        END IF;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Resettable5_process;

  
  Unit_Delay_Enabled_Resettable5_out1 <= '0' WHEN Relational_Operator3_relop1 = '1' ELSE
      Unit_Delay_Enabled_Resettable5_switch_delay;

  -- Free running, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  HDL_Counter8_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      HDL_Counter8_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Relational_Operator3_relop1 = '1' THEN 
          HDL_Counter8_out1 <= '0';
        ELSIF Unit_Delay_Enabled_Resettable5_out1 = '1' THEN 
          HDL_Counter8_out1 <=  NOT HDL_Counter8_out1;
        END IF;
      END IF;
    END IF;
  END PROCESS HDL_Counter8_process;


  
  Compare_To_Constant2_out1 <= '1' WHEN HDL_Counter8_out1 = '1' ELSE
      '0';

  
  Relational_Operator3_relop1 <= '1' WHEN Add4_out1 = resize(HDL_Counter3_out1, 9) ELSE
      '0';

  -- Free running, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  HDL_Counter3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      HDL_Counter3_out1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Relational_Operator3_relop1 = '1' THEN 
          HDL_Counter3_out1 <= to_unsigned(16#00#, 8);
        ELSIF Compare_To_Constant2_out1 = '1' THEN 
          HDL_Counter3_out1 <= HDL_Counter3_out1 + to_unsigned(16#01#, 8);
        END IF;
      END IF;
    END IF;
  END PROCESS HDL_Counter3_process;


  
  Compare_To_Constant6_out1 <= '1' WHEN HDL_Counter3_out1 = to_unsigned(16#01#, 8) ELSE
      '0';

  Constant14_out1 <= to_unsigned(16#00#, 8);

  Bit_Slice5_out1 <= Unit_Delay_Enabled_Resettable1_out1(17 DOWNTO 10);

  
  Switch9_out1 <= Constant14_out1 WHEN Compare_To_Constant9_out1 = '0' ELSE
      Bit_Slice5_out1;

  Delay4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay4_reg <= (OTHERS => to_unsigned(16#00#, 8));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay4_reg(0) <= Switch9_out1;
        Delay4_reg(1 TO 2) <= Delay4_reg(0 TO 1);
      END IF;
    END IF;
  END PROCESS Delay4_process;

  Delay4_out1 <= Delay4_reg(2);

  Unit_Delay_Enabled_Resettable6_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Resettable6_switch_delay <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Logical_Operator3_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable6_switch_delay <= to_unsigned(16#00#, 8);
        ELSIF Compare_To_Constant6_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable6_switch_delay <= Delay4_out1;
        END IF;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Resettable6_process;

  
  Unit_Delay_Enabled_Resettable6_out1 <= to_unsigned(16#00#, 8) WHEN Logical_Operator3_out1 = '1' ELSE
      Unit_Delay_Enabled_Resettable6_switch_delay;

  Out1 <= std_logic_vector(Unit_Delay_Enabled_Resettable6_out1);

  
  Compare_To_Constant7_out1 <= '1' WHEN HDL_Counter3_out1 = to_unsigned(16#02#, 8) ELSE
      '0';

  Unit_Delay_Enabled_Resettable7_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Resettable7_switch_delay <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Logical_Operator3_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable7_switch_delay <= to_unsigned(16#00#, 8);
        ELSIF Compare_To_Constant7_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable7_switch_delay <= Delay4_out1;
        END IF;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Resettable7_process;

  
  Unit_Delay_Enabled_Resettable7_out1 <= to_unsigned(16#00#, 8) WHEN Logical_Operator3_out1 = '1' ELSE
      Unit_Delay_Enabled_Resettable7_switch_delay;

  Out2 <= std_logic_vector(Unit_Delay_Enabled_Resettable7_out1);

  
  Compare_To_Constant8_out1 <= '1' WHEN HDL_Counter3_out1 = to_unsigned(16#03#, 8) ELSE
      '0';

  Unit_Delay_Enabled_Resettable8_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Resettable8_switch_delay <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Logical_Operator3_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable8_switch_delay <= to_unsigned(16#00#, 8);
        ELSIF Compare_To_Constant8_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable8_switch_delay <= Delay4_out1;
        END IF;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Resettable8_process;

  
  Unit_Delay_Enabled_Resettable8_out1 <= to_unsigned(16#00#, 8) WHEN Logical_Operator3_out1 = '1' ELSE
      Unit_Delay_Enabled_Resettable8_switch_delay;

  Out3 <= std_logic_vector(Unit_Delay_Enabled_Resettable8_out1);

  
  Compare_To_Constant11_out1 <= '1' WHEN HDL_Counter3_out1 = to_unsigned(16#04#, 8) ELSE
      '0';

  Unit_Delay_Enabled_Resettable9_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Resettable9_switch_delay <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Logical_Operator3_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable9_switch_delay <= to_unsigned(16#00#, 8);
        ELSIF Compare_To_Constant11_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable9_switch_delay <= Delay4_out1;
        END IF;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Resettable9_process;

  
  Unit_Delay_Enabled_Resettable9_out1 <= to_unsigned(16#00#, 8) WHEN Logical_Operator3_out1 = '1' ELSE
      Unit_Delay_Enabled_Resettable9_switch_delay;

  Out4 <= std_logic_vector(Unit_Delay_Enabled_Resettable9_out1);

  
  Compare_To_Constant14_out1 <= '1' WHEN HDL_Counter3_out1 = to_unsigned(16#05#, 8) ELSE
      '0';

  Unit_Delay_Enabled_Resettable10_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Resettable10_switch_delay <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Logical_Operator3_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable10_switch_delay <= to_unsigned(16#00#, 8);
        ELSIF Compare_To_Constant14_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable10_switch_delay <= Delay4_out1;
        END IF;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Resettable10_process;

  
  Unit_Delay_Enabled_Resettable10_out1 <= to_unsigned(16#00#, 8) WHEN Logical_Operator3_out1 = '1' ELSE
      Unit_Delay_Enabled_Resettable10_switch_delay;

  Out5 <= std_logic_vector(Unit_Delay_Enabled_Resettable10_out1);

  
  Compare_To_Constant15_out1 <= '1' WHEN HDL_Counter3_out1 = to_unsigned(16#06#, 8) ELSE
      '0';

  Unit_Delay_Enabled_Resettable11_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Resettable11_switch_delay <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Logical_Operator3_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable11_switch_delay <= to_unsigned(16#00#, 8);
        ELSIF Compare_To_Constant15_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable11_switch_delay <= Delay4_out1;
        END IF;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Resettable11_process;

  
  Unit_Delay_Enabled_Resettable11_out1 <= to_unsigned(16#00#, 8) WHEN Logical_Operator3_out1 = '1' ELSE
      Unit_Delay_Enabled_Resettable11_switch_delay;

  Out6 <= std_logic_vector(Unit_Delay_Enabled_Resettable11_out1);

  
  Compare_To_Constant16_out1 <= '1' WHEN HDL_Counter3_out1 = to_unsigned(16#07#, 8) ELSE
      '0';

  Unit_Delay_Enabled_Resettable12_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Resettable12_switch_delay <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Logical_Operator3_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable12_switch_delay <= to_unsigned(16#00#, 8);
        ELSIF Compare_To_Constant16_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable12_switch_delay <= Delay4_out1;
        END IF;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Resettable12_process;

  
  Unit_Delay_Enabled_Resettable12_out1 <= to_unsigned(16#00#, 8) WHEN Logical_Operator3_out1 = '1' ELSE
      Unit_Delay_Enabled_Resettable12_switch_delay;

  Out7 <= std_logic_vector(Unit_Delay_Enabled_Resettable12_out1);

  
  Compare_To_Constant17_out1 <= '1' WHEN HDL_Counter3_out1 = to_unsigned(16#08#, 8) ELSE
      '0';

  Unit_Delay_Enabled_Resettable13_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Resettable13_switch_delay <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Logical_Operator3_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable13_switch_delay <= to_unsigned(16#00#, 8);
        ELSIF Compare_To_Constant17_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable13_switch_delay <= Delay4_out1;
        END IF;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Resettable13_process;

  
  Unit_Delay_Enabled_Resettable13_out1 <= to_unsigned(16#00#, 8) WHEN Logical_Operator3_out1 = '1' ELSE
      Unit_Delay_Enabled_Resettable13_switch_delay;

  Out8 <= std_logic_vector(Unit_Delay_Enabled_Resettable13_out1);

  Delay5_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay5_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay5_out1 <= signal_edg4_out1;
      END IF;
    END IF;
  END PROCESS Delay5_process;


  Constant12_out1 <= to_unsigned(16#00#, 8);

  Add7_out1 <= resize(Constant12_out1, 9) + resize(Unit_Delay_Enabled_Resettable15_out1, 9);

  -- Free running, Unsigned Counter
  --  initial value   = 255
  --  step value      = 1
  HDL_Counter10_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      HDL_Counter10_out1 <= to_unsigned(16#FF#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF signal_edg3_out1 = '1' THEN 
          HDL_Counter10_out1 <= to_unsigned(16#FF#, 8);
        ELSIF signal_edg12_out1 = '1' THEN 
          HDL_Counter10_out1 <= HDL_Counter10_out1 + to_unsigned(16#01#, 8);
        END IF;
      END IF;
    END IF;
  END PROCESS HDL_Counter10_process;


  
  Relational_Operator7_relop1 <= '1' WHEN resize(HDL_Counter10_out1, 9) = Add7_out1 ELSE
      '0';

  Logical_Operator26_out1 <= Relational_Operator7_relop1 AND Compare_To_Constant19_out1;

  
  Compare_To_Constant25_out1 <= '1' WHEN AdrrIN_unsigned = to_unsigned(16#06#, 8) ELSE
      '0';

  Delay17_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay17_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay17_out1 <= signal_edg11_out1;
      END IF;
    END IF;
  END PROCESS Delay17_process;


  Logical_Operator30_out1 <= Logical_Operator3_out1 OR Delay17_out1;

  Unit_Delay_Enabled_Resettable25_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Resettable25_switch_delay <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Logical_Operator30_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable25_switch_delay <= to_unsigned(0, 32);
        ELSIF Compare_To_Constant25_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable25_switch_delay <= DataIN_unsigned;
        END IF;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Resettable25_process;

  
  Unit_Delay_Enabled_Resettable25_out1 <= to_unsigned(0, 32) WHEN Logical_Operator30_out1 = '1' ELSE
      Unit_Delay_Enabled_Resettable25_switch_delay;

  
  Compare_To_Constant26_out1 <= '1' WHEN Unit_Delay_Enabled_Resettable25_out1 = to_unsigned(1, 32) ELSE
      '0';

  Logical_Operator23_out1 <= signal_edg11_out1 OR (Delay5_out1 OR Logical_Operator26_out1);

  Unit_Delay_Enabled_Resettable14_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Resettable14_switch_delay <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF RST_IRQ = '1' THEN
          Unit_Delay_Enabled_Resettable14_switch_delay <= '0';
        ELSIF Logical_Operator23_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable14_switch_delay <= Logical_Operator23_out1;
        END IF;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Resettable14_process;

  
  Unit_Delay_Enabled_Resettable14_out1 <= '0' WHEN RST_IRQ = '1' ELSE
      Unit_Delay_Enabled_Resettable14_switch_delay;

  Constant11_out1 <= to_unsigned(16#04#, 8);

  addr_mux <= std_logic_vector(Constant11_out1);

  Constant8_out1 <= to_unsigned(1, 32);

  Constant6_out1 <= to_unsigned(0, 32);

  
  Switch5_out1 <= Constant8_out1 WHEN RD = '0' ELSE
      Constant6_out1;

  data_mux <= std_logic_vector(Switch5_out1);

  Constant31_out1 <= to_unsigned(0, 32);

  Constant30_out1 <= to_unsigned(1, 32);

  
  Switch11_out1 <= Constant31_out1 WHEN Delay5_out1 = '0' ELSE
      Constant30_out1;

  Constant33_out1 <= to_unsigned(0, 32);

  Constant32_out1 <= to_unsigned(2, 32);

  
  Switch15_out1 <= Constant33_out1 WHEN Logical_Operator26_out1 = '0' ELSE
      Constant32_out1;

  Constant38_out1 <= to_unsigned(0, 32);

  Constant37_out1 <= to_unsigned(3, 32);

  
  Switch19_out1 <= Constant38_out1 WHEN signal_edg11_out1 = '0' ELSE
      Constant37_out1;

  Add6_add_temp <= resize(Switch11_out1, 34) + resize(Switch15_out1, 34);
  Add6_out1 <= Add6_add_temp + resize(Switch19_out1, 34);

  Data_Type_Conversion12_out1 <= Add6_out1(31 DOWNTO 0);

  Unit_Delay_Enabled_Resettable26_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Resettable26_switch_delay <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF RST_IRQ = '1' THEN
          Unit_Delay_Enabled_Resettable26_switch_delay <= to_unsigned(0, 32);
        ELSIF Logical_Operator23_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable26_switch_delay <= Data_Type_Conversion12_out1;
        END IF;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Resettable26_process;

  
  Unit_Delay_Enabled_Resettable26_out1 <= to_unsigned(0, 32) WHEN RST_IRQ = '1' ELSE
      Unit_Delay_Enabled_Resettable26_switch_delay;

  STATUS <= std_logic_vector(Unit_Delay_Enabled_Resettable26_out1);

  Logical_Operator25_out1 <=  NOT Relational_Operator6_relop1;

  Logical_Operator32_out1 <= Logical_Operator25_out1 AND Compare_To_Constant22_out1;

  irq <= Unit_Delay_Enabled_Resettable14_out1;

  rd_switch <= Logical_Operator32_out1;

END rtl;

