-- -------------------------------------------------------------
-- 
-- File Name: D:\Matlab_Vhd\smartCart\OTLADKA\hdlsrc\smartCart4_work\head_ip_src_Reciver.vhd
-- Created: 2016-07-20 16:07:08
-- 
-- Generated by MATLAB 9.0 and HDL Coder 3.8
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: head_ip_src_Reciver
-- Source Path: smartCart4_work/head/Reciver
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY head_ip_src_Reciver IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        RST                               :   IN    std_logic_vector(3 DOWNTO 0);  -- sfix4
        IO                                :   IN    std_logic;
        STOP                              :   IN    std_logic;
        adr_IN                            :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        data_in                           :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        ON_RECIVER                        :   IN    std_logic;
        AddrOUT                           :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        STATUS                            :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        Strob                             :   OUT   std_logic
        );
END head_ip_src_Reciver;


ARCHITECTURE rtl OF head_ip_src_Reciver IS

  -- Component Declarations
  COMPONENT head_ip_src_signal_edg
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In1                             :   IN    std_logic;
          Out1                            :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : head_ip_src_signal_edg
    USE ENTITY work.head_ip_src_signal_edg(rtl);

  -- Signals
  SIGNAL Delay1_out1                      : std_logic;
  SIGNAL Logical_Operator5_out1           : std_logic;
  SIGNAL Logical_Operator9_out1           : std_logic;
  SIGNAL signal_edg5_out1                 : std_logic;
  SIGNAL Logical_Operator48_out1          : std_logic;
  SIGNAL RST_signed                       : signed(3 DOWNTO 0);  -- sfix4
  SIGNAL Bit_Slice1_out1                  : std_logic;  -- ufix1
  SIGNAL adr_IN_unsigned                  : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL adr_IN_1                         : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Compare_To_Constant29_out1       : std_logic;
  SIGNAL Constant13_out1                  : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_unsigned                 : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Switch12_out1                    : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Compare_To_Constant30_out1       : std_logic;
  SIGNAL Compare_To_Constant32_out1       : std_logic;
  SIGNAL Unit_Delay_Enabled_Resettable17_switch_delay : std_logic;  -- ufix1
  SIGNAL Unit_Delay_Enabled_Resettable17_out1 : std_logic;
  SIGNAL Logical_Operator47_out1          : std_logic;
  SIGNAL Logical_Operator25_out1          : std_logic;
  SIGNAL Delay_out1                       : std_logic;
  SIGNAL Logical_Operator2_out1           : std_logic;
  SIGNAL Logical_Operator4_out1           : std_logic;
  SIGNAL Logical_Operator3_out1           : std_logic;
  SIGNAL Logical_Operator7_out1           : std_logic;
  SIGNAL Logical_Operator1_out1           : std_logic;
  SIGNAL Unit_Delay_Enabled_Resettable_switch_delay : std_logic;  -- ufix1
  SIGNAL Unit_Delay_Enabled_Resettable_out1 : std_logic;
  SIGNAL Compare_To_Constant4_out1        : std_logic;
  SIGNAL Logical_Operator8_out1           : std_logic;
  SIGNAL HDL_Counter_out1                 : unsigned(12 DOWNTO 0);  -- ufix13
  SIGNAL HDL_Counter2_out1                : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL Logical_Operator11_out1          : std_logic;
  SIGNAL Logical_Operator_out1            : std_logic;
  SIGNAL HDL_Counter2_stepreg             : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL Compare_To_Constant2_out1        : std_logic;
  SIGNAL Delay2_out1                      : std_logic;
  SIGNAL Logical_Operator6_out1           : std_logic;
  SIGNAL Logical_Operator10_out1          : std_logic;
  SIGNAL HDL_Counter1_out1                : std_logic;  -- ufix1
  SIGNAL Compare_To_Constant1_out1        : std_logic;
  SIGNAL Delay3_out1                      : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL Compare_To_Constant3_out1        : std_logic;
  SIGNAL Logical_Operator12_out1          : std_logic;
  SIGNAL Delay5_out1                      : std_logic;
  SIGNAL Unit_Delay_Enabled_Resettable1_switch_delay : std_logic;  -- ufix1
  SIGNAL Unit_Delay_Enabled_Resettable1_out1 : std_logic;
  SIGNAL Compare_To_Constant13_out1       : std_logic;
  SIGNAL Constant9_out1                   : std_logic;
  SIGNAL Logical_Operator22_out1          : std_logic;
  SIGNAL Delay4_out1                      : std_logic;
  SIGNAL Logical_Operator32_out1          : std_logic;
  SIGNAL Logical_Operator33_out1          : std_logic;
  SIGNAL Compare_To_Constant16_out1       : std_logic;
  SIGNAL Constant14_out1                  : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay11_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Switch11_out1                    : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Bit_Slice2_out1                  : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL Compare_To_Constant19_out1       : std_logic;
  SIGNAL Constant7_out1                   : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Switch9_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Bit_Slice4_out1                  : std_logic;  -- ufix1
  SIGNAL Compare_To_Constant20_out1       : std_logic;
  SIGNAL Logical_Operator35_out1          : std_logic;
  SIGNAL Constant1_out1                   : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Constant2_out1                   : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Switch2_out1                     : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Compare_To_Constant31_out1       : std_logic;
  SIGNAL Logical_Operator38_out1          : std_logic;
  SIGNAL signal_edg_out1                  : std_logic;
  SIGNAL Constant16_out1                  : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Constant17_out1                  : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Switch13_out1                    : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Add1_out1                        : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL Data_Type_Conversion10_out1      : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Delay8_out1                      : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Constant12_out1                  : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Constant12_out1_dtc              : unsigned(17 DOWNTO 0);  -- ufix18
  SIGNAL Bit_Slice5_out1                  : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL Data_Type_Conversion1_out1       : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL Compare_To_Constant18_out1       : std_logic;
  SIGNAL Constant3_out1                   : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Bit_Slice3_out1                  : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL Data_Type_Conversion5_out1       : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Switch7_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Data_Type_Conversion6_out1       : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL HDL_Counter3_out1                : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL Compare_To_Constant15_out1       : std_logic;
  SIGNAL Logical_Operator37_out1          : std_logic;
  SIGNAL Logical_Operator36_out1          : std_logic;
  SIGNAL Switch6_out1                     : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL Data_Type_Conversion8_out1       : signed(3 DOWNTO 0);  -- sfix4
  SIGNAL Compare_To_Constant21_out1       : std_logic;
  SIGNAL Constant11_out1                  : std_logic;
  SIGNAL Constant6_out1                   : std_logic;
  SIGNAL Switch5_out1                     : std_logic;
  SIGNAL Logical_Operator39_out1          : std_logic;
  SIGNAL Constant5_out1                   : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Constant_out1                    : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Compare_To_Constant5_out1        : std_logic;
  SIGNAL Logical_Operator13_out1          : std_logic;
  SIGNAL Unit_Delay_Enabled_Resettable2_switch_delay : std_logic;  -- ufix1
  SIGNAL Unit_Delay_Enabled_Resettable2_out1 : std_logic;
  SIGNAL Compare_To_Constant6_out1        : std_logic;
  SIGNAL Logical_Operator14_out1          : std_logic;
  SIGNAL Unit_Delay_Enabled_Resettable3_switch_delay : std_logic;  -- ufix1
  SIGNAL Unit_Delay_Enabled_Resettable3_out1 : std_logic;
  SIGNAL Compare_To_Constant7_out1        : std_logic;
  SIGNAL Logical_Operator15_out1          : std_logic;
  SIGNAL Unit_Delay_Enabled_Resettable4_switch_delay : std_logic;  -- ufix1
  SIGNAL Unit_Delay_Enabled_Resettable4_out1 : std_logic;
  SIGNAL Compare_To_Constant8_out1        : std_logic;
  SIGNAL Logical_Operator16_out1          : std_logic;
  SIGNAL Unit_Delay_Enabled_Resettable5_switch_delay : std_logic;  -- ufix1
  SIGNAL Unit_Delay_Enabled_Resettable5_out1 : std_logic;
  SIGNAL Compare_To_Constant9_out1        : std_logic;
  SIGNAL Logical_Operator17_out1          : std_logic;
  SIGNAL Unit_Delay_Enabled_Resettable6_switch_delay : std_logic;  -- ufix1
  SIGNAL Unit_Delay_Enabled_Resettable6_out1 : std_logic;
  SIGNAL Compare_To_Constant14_out1       : std_logic;
  SIGNAL Logical_Operator18_out1          : std_logic;
  SIGNAL Unit_Delay_Enabled_Resettable7_switch_delay : std_logic;  -- ufix1
  SIGNAL Unit_Delay_Enabled_Resettable7_out1 : std_logic;
  SIGNAL Compare_To_Constant10_out1       : std_logic;
  SIGNAL Logical_Operator19_out1          : std_logic;
  SIGNAL Unit_Delay_Enabled_Resettable8_switch_delay : std_logic;  -- ufix1
  SIGNAL Unit_Delay_Enabled_Resettable8_out1 : std_logic;
  SIGNAL Compare_To_Constant11_out1       : std_logic;
  SIGNAL Logical_Operator20_out1          : std_logic;
  SIGNAL Unit_Delay_Enabled_Resettable9_switch_delay : std_logic;  -- ufix1
  SIGNAL Unit_Delay_Enabled_Resettable9_out1 : std_logic;
  SIGNAL Bit_Concat_out1                  : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Switch1_out1                     : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Switch4_out1                     : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Unit_Delay_Enabled_Resettable11_switch_delay : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL Unit_Delay_Enabled_Resettable11_out1 : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Compare_To_Constant22_out1       : std_logic;
  SIGNAL Logical_Operator40_out1          : std_logic;
  SIGNAL Unit_Delay_Enabled_Resettable12_switch_delay : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL Unit_Delay_Enabled_Resettable12_out1 : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Compare_To_Constant23_out1       : std_logic;
  SIGNAL Logical_Operator41_out1          : std_logic;
  SIGNAL Unit_Delay_Enabled_Resettable13_switch_delay : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL Unit_Delay_Enabled_Resettable13_out1 : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Compare_To_Constant24_out1       : std_logic;
  SIGNAL Logical_Operator42_out1          : std_logic;
  SIGNAL Unit_Delay_Enabled_Resettable14_switch_delay : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL Unit_Delay_Enabled_Resettable14_out1 : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Compare_To_Constant25_out1       : std_logic;
  SIGNAL Logical_Operator43_out1          : std_logic;
  SIGNAL Unit_Delay_Enabled_Resettable15_switch_delay : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL Unit_Delay_Enabled_Resettable15_out1 : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Compare_To_Constant26_out1       : std_logic;
  SIGNAL Logical_Operator44_out1          : std_logic;
  SIGNAL Unit_Delay_Enabled_Resettable16_switch_delay : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL Unit_Delay_Enabled_Resettable16_out1 : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Compare_To_Constant27_out1       : std_logic;
  SIGNAL Logical_Operator45_out1          : std_logic;
  SIGNAL Unit_Delay_Enabled_Resettable18_switch_delay : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL Unit_Delay_Enabled_Resettable18_out1 : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Compare_To_Constant28_out1       : std_logic;
  SIGNAL Logical_Operator46_out1          : std_logic;
  SIGNAL Unit_Delay_Enabled_Resettable19_switch_delay : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL Unit_Delay_Enabled_Resettable19_out1 : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Index_Vector_out1                : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Data_Type_Conversion2_out1       : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Constant8_out1                   : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL Constant4_out1                   : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL Switch10_out1                    : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL Bit_Concat1_out1                 : unsigned(17 DOWNTO 0);  -- ufix18
  SIGNAL Switch3_out1                     : unsigned(17 DOWNTO 0);  -- ufix18
  SIGNAL Data_Type_Conversion4_out1       : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Constant15_out1                  : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Constant18_out1                  : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Constant18_out1_dtc              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Switch14_out1                    : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Add_out1                         : unsigned(32 DOWNTO 0);  -- ufix33
  SIGNAL Data_Type_Conversion9_out1       : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay6_out1                      : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Constant10_out1                  : std_logic;
  SIGNAL Compare_To_Constant17_out1       : std_logic;
  SIGNAL Switch8_out1                     : std_logic;
  SIGNAL SA12_out1                        : std_logic;
  SIGNAL HDL_Counter4_out1                : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Logical_Operator34_out1          : std_logic;

BEGIN
  -- Cхема формирования байта и проверка четности
  -- 
  -- Схема связи (5)
  -- 
  -- Схема формирования отчёта о работе приёмника (4)
  -- 
  -- cхема управления и синхронизации (2)
  -- 
  -- Схема обнаружение сообщения (1)

  u_signal_edg5 : head_ip_src_signal_edg
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              In1 => ON_RECIVER,
              Out1 => signal_edg5_out1
              );

  u_signal_edg : head_ip_src_signal_edg
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              In1 => Logical_Operator38_out1,
              Out1 => signal_edg_out1
              );

  Delay1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay1_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay1_out1 <= STOP;
      END IF;
    END IF;
  END PROCESS Delay1_process;


  Logical_Operator5_out1 <= Delay1_out1 XOR STOP;

  Logical_Operator9_out1 <= Logical_Operator5_out1 AND STOP;

  Logical_Operator48_out1 <= Logical_Operator9_out1 OR signal_edg5_out1;

  RST_signed <= signed(RST);

  Bit_Slice1_out1 <= RST_signed(3);

  adr_IN_unsigned <= unsigned(adr_IN);

  reduced_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      adr_IN_1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        adr_IN_1 <= adr_IN_unsigned;
      END IF;
    END IF;
  END PROCESS reduced_process;


  
  Compare_To_Constant29_out1 <= '1' WHEN adr_IN_1 = to_unsigned(16#05#, 8) ELSE
      '0';

  Constant13_out1 <= to_unsigned(0, 32);

  data_in_unsigned <= unsigned(data_in);

  
  Switch12_out1 <= Constant13_out1 WHEN Compare_To_Constant29_out1 = '0' ELSE
      data_in_unsigned;

  
  Compare_To_Constant30_out1 <= '1' WHEN Switch12_out1 = to_unsigned(1, 32) ELSE
      '0';

  
  Compare_To_Constant32_out1 <= '1' WHEN Switch12_out1 = to_unsigned(0, 32) ELSE
      '0';

  Unit_Delay_Enabled_Resettable17_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Resettable17_switch_delay <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Compare_To_Constant32_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable17_switch_delay <= '0';
        ELSIF Compare_To_Constant30_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable17_switch_delay <= Compare_To_Constant30_out1;
        END IF;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Resettable17_process;

  
  Unit_Delay_Enabled_Resettable17_out1 <= '0' WHEN Compare_To_Constant32_out1 = '1' ELSE
      Unit_Delay_Enabled_Resettable17_switch_delay;

  Logical_Operator47_out1 <=  NOT Unit_Delay_Enabled_Resettable17_out1;

  Logical_Operator25_out1 <= Logical_Operator47_out1 AND (Bit_Slice1_out1 AND IO);

  Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay_out1 <= Logical_Operator25_out1;
      END IF;
    END IF;
  END PROCESS Delay_process;


  Logical_Operator2_out1 <= Delay_out1 XOR Logical_Operator25_out1;

  Logical_Operator4_out1 <=  NOT Logical_Operator25_out1;

  Logical_Operator3_out1 <= Logical_Operator2_out1 AND Logical_Operator4_out1;

  Logical_Operator1_out1 <= Logical_Operator7_out1 OR Logical_Operator9_out1;

  Unit_Delay_Enabled_Resettable_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Resettable_switch_delay <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Logical_Operator1_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable_switch_delay <= '0';
        ELSIF Logical_Operator3_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable_switch_delay <= Logical_Operator3_out1;
        END IF;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Resettable_process;

  
  Unit_Delay_Enabled_Resettable_out1 <= '0' WHEN Logical_Operator1_out1 = '1' ELSE
      Unit_Delay_Enabled_Resettable_switch_delay;

  Logical_Operator8_out1 <= Logical_Operator48_out1 OR (Compare_To_Constant4_out1 OR Logical_Operator7_out1);

  -- Free running, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  HDL_Counter_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      HDL_Counter_out1 <= to_unsigned(16#0000#, 13);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Logical_Operator8_out1 = '1' THEN 
          HDL_Counter_out1 <= to_unsigned(16#0000#, 13);
        ELSIF Unit_Delay_Enabled_Resettable_out1 = '1' THEN 
          HDL_Counter_out1 <= HDL_Counter_out1 + to_unsigned(16#0001#, 13);
        END IF;
      END IF;
    END IF;
  END PROCESS HDL_Counter_process;


  
  Compare_To_Constant4_out1 <= '1' WHEN HDL_Counter_out1 = to_unsigned(16#0A2C#, 13) ELSE
      '0';

  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 10
  HDL_Counter2_step_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      HDL_Counter2_stepreg <= to_unsigned(16#1#, 4);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Logical_Operator11_out1 = '1' THEN 
          HDL_Counter2_stepreg <= to_unsigned(16#1#, 4);
        ELSIF Logical_Operator_out1 = '1' THEN 
          IF HDL_Counter2_out1 = to_unsigned(16#9#, 4) THEN 
            HDL_Counter2_stepreg <= to_unsigned(16#6#, 4);
          ELSE 
            HDL_Counter2_stepreg <= to_unsigned(16#1#, 4);
          END IF;
        END IF;
      END IF;
    END IF;
  END PROCESS HDL_Counter2_step_process;


  Logical_Operator11_out1 <= Logical_Operator7_out1 OR Logical_Operator48_out1;

  HDL_Counter2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      HDL_Counter2_out1 <= to_unsigned(16#0#, 4);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Logical_Operator11_out1 = '1' THEN 
          HDL_Counter2_out1 <= to_unsigned(16#0#, 4);
        ELSIF Logical_Operator_out1 = '1' THEN 
          HDL_Counter2_out1 <= HDL_Counter2_out1 + HDL_Counter2_stepreg;
        END IF;
      END IF;
    END IF;
  END PROCESS HDL_Counter2_process;


  
  Compare_To_Constant2_out1 <= '1' WHEN HDL_Counter2_out1 = to_unsigned(16#A#, 4) ELSE
      '0';

  Delay2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay2_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay2_out1 <= Compare_To_Constant2_out1;
      END IF;
    END IF;
  END PROCESS Delay2_process;


  Logical_Operator6_out1 <= Delay2_out1 XOR Compare_To_Constant2_out1;

  Logical_Operator7_out1 <= Logical_Operator6_out1 AND Compare_To_Constant2_out1;

  Logical_Operator10_out1 <= Logical_Operator7_out1 OR Logical_Operator48_out1;

  -- Free running, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  HDL_Counter1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      HDL_Counter1_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Logical_Operator10_out1 = '1' THEN 
          HDL_Counter1_out1 <= '0';
        ELSIF Compare_To_Constant4_out1 = '1' THEN 
          HDL_Counter1_out1 <=  NOT HDL_Counter1_out1;
        END IF;
      END IF;
    END IF;
  END PROCESS HDL_Counter1_process;


  
  Compare_To_Constant1_out1 <= '1' WHEN HDL_Counter1_out1 = '0' ELSE
      '0';

  Logical_Operator_out1 <= Compare_To_Constant1_out1 AND Compare_To_Constant4_out1;

  Delay3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay3_out1 <= to_unsigned(16#0#, 4);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay3_out1 <= HDL_Counter2_out1;
      END IF;
    END IF;
  END PROCESS Delay3_process;


  
  Compare_To_Constant3_out1 <= '1' WHEN Delay3_out1 = to_unsigned(16#0#, 4) ELSE
      '0';

  Logical_Operator12_out1 <= Logical_Operator_out1 AND Compare_To_Constant3_out1;

  Delay5_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay5_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay5_out1 <= Logical_Operator7_out1;
      END IF;
    END IF;
  END PROCESS Delay5_process;


  Unit_Delay_Enabled_Resettable1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Resettable1_switch_delay <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Delay5_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable1_switch_delay <= '0';
        ELSIF Logical_Operator12_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable1_switch_delay <= IO;
        END IF;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Resettable1_process;

  
  Unit_Delay_Enabled_Resettable1_out1 <= '0' WHEN Delay5_out1 = '1' ELSE
      Unit_Delay_Enabled_Resettable1_switch_delay;

  
  Compare_To_Constant13_out1 <= '1' WHEN Unit_Delay_Enabled_Resettable1_out1 = '0' ELSE
      '0';

  Constant9_out1 <= '1';

  Logical_Operator22_out1 <= Constant9_out1 AND (Compare_To_Constant13_out1 AND Logical_Operator7_out1);

  Delay4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay4_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay4_out1 <= Logical_Operator22_out1;
      END IF;
    END IF;
  END PROCESS Delay4_process;


  Logical_Operator32_out1 <= Delay4_out1 XOR Logical_Operator22_out1;

  Logical_Operator33_out1 <= Logical_Operator32_out1 AND Logical_Operator22_out1;

  
  Compare_To_Constant16_out1 <= '1' WHEN adr_IN_1 = to_unsigned(16#01#, 8) ELSE
      '0';

  Constant14_out1 <= to_unsigned(0, 32);

  Delay11_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay11_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay11_out1 <= data_in_unsigned;
      END IF;
    END IF;
  END PROCESS Delay11_process;


  
  Switch11_out1 <= Constant14_out1 WHEN Compare_To_Constant16_out1 = '0' ELSE
      Delay11_out1;

  Bit_Slice2_out1 <= Switch11_out1(1 DOWNTO 0);

  
  Compare_To_Constant19_out1 <= '1' WHEN Bit_Slice2_out1 = to_unsigned(16#2#, 2) ELSE
      '0';

  Constant7_out1 <= to_unsigned(0, 32);

  
  Switch9_out1 <= Constant7_out1 WHEN Compare_To_Constant19_out1 = '0' ELSE
      Switch11_out1;

  Bit_Slice4_out1 <= Switch9_out1(2);

  
  Compare_To_Constant20_out1 <= '1' WHEN Bit_Slice4_out1 = '1' ELSE
      '0';

  Logical_Operator35_out1 <= Logical_Operator33_out1 OR Compare_To_Constant20_out1;

  Constant1_out1 <= to_unsigned(16#00#, 8);

  Constant2_out1 <= to_unsigned(16#01#, 8);

  
  Switch2_out1 <= Constant1_out1 WHEN Logical_Operator35_out1 = '0' ELSE
      Constant2_out1;

  
  Compare_To_Constant31_out1 <= '1' WHEN IO = '0' ELSE
      '0';

  Logical_Operator38_out1 <= Compare_To_Constant31_out1 AND Unit_Delay_Enabled_Resettable17_out1;

  Constant16_out1 <= to_unsigned(16#00#, 8);

  Constant17_out1 <= to_unsigned(16#05#, 8);

  
  Switch13_out1 <= Constant16_out1 WHEN signal_edg_out1 = '0' ELSE
      Constant17_out1;

  Add1_out1 <= resize(Switch2_out1, 9) + resize(Switch13_out1, 9);

  Data_Type_Conversion10_out1 <= Add1_out1(7 DOWNTO 0);

  Delay8_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay8_out1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay8_out1 <= Data_Type_Conversion10_out1;
      END IF;
    END IF;
  END PROCESS Delay8_process;


  AddrOUT <= std_logic_vector(Delay8_out1);

  Constant12_out1 <= to_unsigned(16#00#, 8);

  Constant12_out1_dtc <= resize(Constant12_out1, 18);

  Bit_Slice5_out1 <= Switch9_out1(8 DOWNTO 3);

  Data_Type_Conversion1_out1 <= Bit_Slice5_out1(4 DOWNTO 0);

  
  Compare_To_Constant18_out1 <= '1' WHEN Bit_Slice2_out1 = to_unsigned(16#1#, 2) ELSE
      '0';

  Constant3_out1 <= to_unsigned(0, 32);

  Bit_Slice3_out1 <= Switch11_out1(7 DOWNTO 2);

  Data_Type_Conversion5_out1 <= resize(Bit_Slice3_out1, 32);

  
  Switch7_out1 <= Constant3_out1 WHEN Compare_To_Constant18_out1 = '0' ELSE
      Data_Type_Conversion5_out1;

  Data_Type_Conversion6_out1 <= Switch7_out1(4 DOWNTO 0);

  
  Compare_To_Constant15_out1 <= '1' WHEN HDL_Counter3_out1 = to_unsigned(16#07#, 5) ELSE
      '0';

  Logical_Operator37_out1 <=  NOT Compare_To_Constant15_out1;

  Logical_Operator36_out1 <= Logical_Operator22_out1 AND Logical_Operator37_out1;

  -- Free running, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  HDL_Counter3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      HDL_Counter3_out1 <= to_unsigned(16#00#, 5);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Logical_Operator48_out1 = '1' THEN 
          HDL_Counter3_out1 <= to_unsigned(16#00#, 5);
        ELSIF Compare_To_Constant18_out1 = '1' THEN 
          HDL_Counter3_out1 <= Data_Type_Conversion6_out1;
        ELSIF Logical_Operator36_out1 = '1' THEN 
          HDL_Counter3_out1 <= HDL_Counter3_out1 + to_unsigned(16#01#, 5);
        END IF;
      END IF;
    END IF;
  END PROCESS HDL_Counter3_process;


  
  Switch6_out1 <= Data_Type_Conversion1_out1 WHEN Logical_Operator22_out1 = '0' ELSE
      HDL_Counter3_out1;

  Data_Type_Conversion8_out1 <= signed(Switch6_out1(3 DOWNTO 0));

  
  Compare_To_Constant21_out1 <= '1' WHEN Switch6_out1 = to_unsigned(16#00#, 5) ELSE
      '0';

  Constant11_out1 <= '0';

  Constant6_out1 <= '1';

  
  Switch5_out1 <= Constant11_out1 WHEN Logical_Operator22_out1 = '0' ELSE
      Constant6_out1;

  Logical_Operator39_out1 <= Compare_To_Constant21_out1 AND Switch5_out1;

  Constant5_out1 <= to_unsigned(16#00#, 8);

  Constant_out1 <= to_unsigned(16#00#, 8);

  
  Compare_To_Constant5_out1 <= '1' WHEN Delay3_out1 = to_unsigned(16#1#, 4) ELSE
      '0';

  Logical_Operator13_out1 <= Compare_To_Constant5_out1 AND Logical_Operator_out1;

  Unit_Delay_Enabled_Resettable2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Resettable2_switch_delay <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Delay5_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable2_switch_delay <= '0';
        ELSIF Logical_Operator13_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable2_switch_delay <= IO;
        END IF;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Resettable2_process;

  
  Unit_Delay_Enabled_Resettable2_out1 <= '0' WHEN Delay5_out1 = '1' ELSE
      Unit_Delay_Enabled_Resettable2_switch_delay;

  
  Compare_To_Constant6_out1 <= '1' WHEN Delay3_out1 = to_unsigned(16#2#, 4) ELSE
      '0';

  Logical_Operator14_out1 <= Compare_To_Constant6_out1 AND Logical_Operator_out1;

  Unit_Delay_Enabled_Resettable3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Resettable3_switch_delay <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Delay5_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable3_switch_delay <= '0';
        ELSIF Logical_Operator14_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable3_switch_delay <= IO;
        END IF;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Resettable3_process;

  
  Unit_Delay_Enabled_Resettable3_out1 <= '0' WHEN Delay5_out1 = '1' ELSE
      Unit_Delay_Enabled_Resettable3_switch_delay;

  
  Compare_To_Constant7_out1 <= '1' WHEN Delay3_out1 = to_unsigned(16#3#, 4) ELSE
      '0';

  Logical_Operator15_out1 <= Compare_To_Constant7_out1 AND Logical_Operator_out1;

  Unit_Delay_Enabled_Resettable4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Resettable4_switch_delay <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Delay5_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable4_switch_delay <= '0';
        ELSIF Logical_Operator15_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable4_switch_delay <= IO;
        END IF;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Resettable4_process;

  
  Unit_Delay_Enabled_Resettable4_out1 <= '0' WHEN Delay5_out1 = '1' ELSE
      Unit_Delay_Enabled_Resettable4_switch_delay;

  
  Compare_To_Constant8_out1 <= '1' WHEN Delay3_out1 = to_unsigned(16#4#, 4) ELSE
      '0';

  Logical_Operator16_out1 <= Compare_To_Constant8_out1 AND Logical_Operator_out1;

  Unit_Delay_Enabled_Resettable5_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Resettable5_switch_delay <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Delay5_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable5_switch_delay <= '0';
        ELSIF Logical_Operator16_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable5_switch_delay <= IO;
        END IF;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Resettable5_process;

  
  Unit_Delay_Enabled_Resettable5_out1 <= '0' WHEN Delay5_out1 = '1' ELSE
      Unit_Delay_Enabled_Resettable5_switch_delay;

  
  Compare_To_Constant9_out1 <= '1' WHEN Delay3_out1 = to_unsigned(16#5#, 4) ELSE
      '0';

  Logical_Operator17_out1 <= Compare_To_Constant9_out1 AND Logical_Operator_out1;

  Unit_Delay_Enabled_Resettable6_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Resettable6_switch_delay <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Delay5_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable6_switch_delay <= '0';
        ELSIF Logical_Operator17_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable6_switch_delay <= IO;
        END IF;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Resettable6_process;

  
  Unit_Delay_Enabled_Resettable6_out1 <= '0' WHEN Delay5_out1 = '1' ELSE
      Unit_Delay_Enabled_Resettable6_switch_delay;

  
  Compare_To_Constant14_out1 <= '1' WHEN Delay3_out1 = to_unsigned(16#6#, 4) ELSE
      '0';

  Logical_Operator18_out1 <= Compare_To_Constant14_out1 AND Logical_Operator_out1;

  Unit_Delay_Enabled_Resettable7_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Resettable7_switch_delay <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Delay5_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable7_switch_delay <= '0';
        ELSIF Logical_Operator18_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable7_switch_delay <= IO;
        END IF;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Resettable7_process;

  
  Unit_Delay_Enabled_Resettable7_out1 <= '0' WHEN Delay5_out1 = '1' ELSE
      Unit_Delay_Enabled_Resettable7_switch_delay;

  
  Compare_To_Constant10_out1 <= '1' WHEN Delay3_out1 = to_unsigned(16#7#, 4) ELSE
      '0';

  Logical_Operator19_out1 <= Compare_To_Constant10_out1 AND Logical_Operator_out1;

  Unit_Delay_Enabled_Resettable8_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Resettable8_switch_delay <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Delay5_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable8_switch_delay <= '0';
        ELSIF Logical_Operator19_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable8_switch_delay <= IO;
        END IF;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Resettable8_process;

  
  Unit_Delay_Enabled_Resettable8_out1 <= '0' WHEN Delay5_out1 = '1' ELSE
      Unit_Delay_Enabled_Resettable8_switch_delay;

  
  Compare_To_Constant11_out1 <= '1' WHEN Delay3_out1 = to_unsigned(16#8#, 4) ELSE
      '0';

  Logical_Operator20_out1 <= Compare_To_Constant11_out1 AND Logical_Operator_out1;

  Unit_Delay_Enabled_Resettable9_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Resettable9_switch_delay <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Delay5_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable9_switch_delay <= '0';
        ELSIF Logical_Operator20_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable9_switch_delay <= IO;
        END IF;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Resettable9_process;

  
  Unit_Delay_Enabled_Resettable9_out1 <= '0' WHEN Delay5_out1 = '1' ELSE
      Unit_Delay_Enabled_Resettable9_switch_delay;

  Bit_Concat_out1 <= unsigned'(Unit_Delay_Enabled_Resettable2_out1 & Unit_Delay_Enabled_Resettable3_out1 & Unit_Delay_Enabled_Resettable4_out1 & Unit_Delay_Enabled_Resettable5_out1 & Unit_Delay_Enabled_Resettable6_out1 & Unit_Delay_Enabled_Resettable7_out1 & Unit_Delay_Enabled_Resettable8_out1 & Unit_Delay_Enabled_Resettable9_out1);

  
  Switch1_out1 <= Constant_out1 WHEN Logical_Operator22_out1 = '0' ELSE
      Bit_Concat_out1;

  
  Switch4_out1 <= Constant5_out1 WHEN Logical_Operator22_out1 = '0' ELSE
      Switch1_out1;

  Unit_Delay_Enabled_Resettable11_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Resettable11_switch_delay <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Logical_Operator48_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable11_switch_delay <= to_unsigned(16#00#, 8);
        ELSIF Logical_Operator39_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable11_switch_delay <= Switch4_out1;
        END IF;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Resettable11_process;

  
  Unit_Delay_Enabled_Resettable11_out1 <= to_unsigned(16#00#, 8) WHEN Logical_Operator48_out1 = '1' ELSE
      Unit_Delay_Enabled_Resettable11_switch_delay;

  
  Compare_To_Constant22_out1 <= '1' WHEN Switch6_out1 = to_unsigned(16#01#, 5) ELSE
      '0';

  Logical_Operator40_out1 <= Compare_To_Constant22_out1 AND Switch5_out1;

  Unit_Delay_Enabled_Resettable12_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Resettable12_switch_delay <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Logical_Operator48_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable12_switch_delay <= to_unsigned(16#00#, 8);
        ELSIF Logical_Operator40_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable12_switch_delay <= Switch4_out1;
        END IF;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Resettable12_process;

  
  Unit_Delay_Enabled_Resettable12_out1 <= to_unsigned(16#00#, 8) WHEN Logical_Operator48_out1 = '1' ELSE
      Unit_Delay_Enabled_Resettable12_switch_delay;

  
  Compare_To_Constant23_out1 <= '1' WHEN Switch6_out1 = to_unsigned(16#02#, 5) ELSE
      '0';

  Logical_Operator41_out1 <= Compare_To_Constant23_out1 AND Switch5_out1;

  Unit_Delay_Enabled_Resettable13_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Resettable13_switch_delay <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Logical_Operator48_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable13_switch_delay <= to_unsigned(16#00#, 8);
        ELSIF Logical_Operator41_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable13_switch_delay <= Switch4_out1;
        END IF;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Resettable13_process;

  
  Unit_Delay_Enabled_Resettable13_out1 <= to_unsigned(16#00#, 8) WHEN Logical_Operator48_out1 = '1' ELSE
      Unit_Delay_Enabled_Resettable13_switch_delay;

  
  Compare_To_Constant24_out1 <= '1' WHEN Switch6_out1 = to_unsigned(16#03#, 5) ELSE
      '0';

  Logical_Operator42_out1 <= Compare_To_Constant24_out1 AND Switch5_out1;

  Unit_Delay_Enabled_Resettable14_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Resettable14_switch_delay <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Logical_Operator48_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable14_switch_delay <= to_unsigned(16#00#, 8);
        ELSIF Logical_Operator42_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable14_switch_delay <= Switch4_out1;
        END IF;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Resettable14_process;

  
  Unit_Delay_Enabled_Resettable14_out1 <= to_unsigned(16#00#, 8) WHEN Logical_Operator48_out1 = '1' ELSE
      Unit_Delay_Enabled_Resettable14_switch_delay;

  
  Compare_To_Constant25_out1 <= '1' WHEN Switch6_out1 = to_unsigned(16#04#, 5) ELSE
      '0';

  Logical_Operator43_out1 <= Compare_To_Constant25_out1 AND Switch5_out1;

  Unit_Delay_Enabled_Resettable15_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Resettable15_switch_delay <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Logical_Operator48_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable15_switch_delay <= to_unsigned(16#00#, 8);
        ELSIF Logical_Operator43_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable15_switch_delay <= Switch4_out1;
        END IF;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Resettable15_process;

  
  Unit_Delay_Enabled_Resettable15_out1 <= to_unsigned(16#00#, 8) WHEN Logical_Operator48_out1 = '1' ELSE
      Unit_Delay_Enabled_Resettable15_switch_delay;

  
  Compare_To_Constant26_out1 <= '1' WHEN Switch6_out1 = to_unsigned(16#05#, 5) ELSE
      '0';

  Logical_Operator44_out1 <= Compare_To_Constant26_out1 AND Switch5_out1;

  Unit_Delay_Enabled_Resettable16_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Resettable16_switch_delay <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Logical_Operator48_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable16_switch_delay <= to_unsigned(16#00#, 8);
        ELSIF Logical_Operator44_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable16_switch_delay <= Switch4_out1;
        END IF;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Resettable16_process;

  
  Unit_Delay_Enabled_Resettable16_out1 <= to_unsigned(16#00#, 8) WHEN Logical_Operator48_out1 = '1' ELSE
      Unit_Delay_Enabled_Resettable16_switch_delay;

  
  Compare_To_Constant27_out1 <= '1' WHEN Switch6_out1 = to_unsigned(16#06#, 5) ELSE
      '0';

  Logical_Operator45_out1 <= Compare_To_Constant27_out1 AND Switch5_out1;

  Unit_Delay_Enabled_Resettable18_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Resettable18_switch_delay <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Logical_Operator48_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable18_switch_delay <= to_unsigned(16#00#, 8);
        ELSIF Logical_Operator45_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable18_switch_delay <= Switch4_out1;
        END IF;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Resettable18_process;

  
  Unit_Delay_Enabled_Resettable18_out1 <= to_unsigned(16#00#, 8) WHEN Logical_Operator48_out1 = '1' ELSE
      Unit_Delay_Enabled_Resettable18_switch_delay;

  
  Compare_To_Constant28_out1 <= '1' WHEN Switch6_out1 = to_unsigned(16#07#, 5) ELSE
      '0';

  Logical_Operator46_out1 <= Compare_To_Constant28_out1 AND Switch5_out1;

  Unit_Delay_Enabled_Resettable19_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Resettable19_switch_delay <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Logical_Operator48_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable19_switch_delay <= to_unsigned(16#00#, 8);
        ELSIF Logical_Operator46_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable19_switch_delay <= Switch4_out1;
        END IF;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Resettable19_process;

  
  Unit_Delay_Enabled_Resettable19_out1 <= to_unsigned(16#00#, 8) WHEN Logical_Operator48_out1 = '1' ELSE
      Unit_Delay_Enabled_Resettable19_switch_delay;

  
  Index_Vector_out1 <= Unit_Delay_Enabled_Resettable11_out1 WHEN Data_Type_Conversion8_out1 = to_signed(16#0#, 4) ELSE
      Unit_Delay_Enabled_Resettable12_out1 WHEN Data_Type_Conversion8_out1 = to_signed(16#1#, 4) ELSE
      Unit_Delay_Enabled_Resettable13_out1 WHEN Data_Type_Conversion8_out1 = to_signed(16#2#, 4) ELSE
      Unit_Delay_Enabled_Resettable14_out1 WHEN Data_Type_Conversion8_out1 = to_signed(16#3#, 4) ELSE
      Unit_Delay_Enabled_Resettable15_out1 WHEN Data_Type_Conversion8_out1 = to_signed(16#4#, 4) ELSE
      Unit_Delay_Enabled_Resettable16_out1 WHEN Data_Type_Conversion8_out1 = to_signed(16#5#, 4) ELSE
      Unit_Delay_Enabled_Resettable18_out1 WHEN Data_Type_Conversion8_out1 = to_signed(16#6#, 4) ELSE
      Unit_Delay_Enabled_Resettable19_out1;

  Data_Type_Conversion2_out1 <= resize(HDL_Counter3_out1, 8);

  Constant8_out1 <= to_unsigned(16#1#, 2);

  Constant4_out1 <= to_unsigned(16#2#, 2);

  
  Switch10_out1 <= Constant8_out1 WHEN Compare_To_Constant20_out1 = '0' ELSE
      Constant4_out1;

  Bit_Concat1_out1 <= Index_Vector_out1 & Data_Type_Conversion2_out1 & Switch10_out1;

  
  Switch3_out1 <= Constant12_out1_dtc WHEN Logical_Operator35_out1 = '0' ELSE
      Bit_Concat1_out1;

  Data_Type_Conversion4_out1 <= resize(Switch3_out1, 32);

  Constant15_out1 <= to_unsigned(0, 32);

  Constant18_out1 <= to_unsigned(16#01#, 8);

  Constant18_out1_dtc <= resize(Constant18_out1, 32);

  
  Switch14_out1 <= Constant15_out1 WHEN signal_edg_out1 = '0' ELSE
      Constant18_out1_dtc;

  Add_out1 <= resize(Data_Type_Conversion4_out1, 33) + resize(Switch14_out1, 33);

  Data_Type_Conversion9_out1 <= Add_out1(31 DOWNTO 0);

  Delay6_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay6_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay6_out1 <= Data_Type_Conversion9_out1;
      END IF;
    END IF;
  END PROCESS Delay6_process;


  STATUS <= std_logic_vector(Delay6_out1);

  Constant10_out1 <= '0';

  
  Switch8_out1 <= Logical_Operator_out1 WHEN Compare_To_Constant17_out1 = '0' ELSE
      Constant10_out1;

  -- Free running, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  HDL_Counter4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      HDL_Counter4_out1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Compare_To_Constant17_out1 = '1' THEN 
          HDL_Counter4_out1 <= to_unsigned(16#00#, 8);
        ELSIF SA12_out1 = '1' THEN 
          HDL_Counter4_out1 <= HDL_Counter4_out1 + to_unsigned(16#01#, 8);
        END IF;
      END IF;
    END IF;
  END PROCESS HDL_Counter4_process;


  
  Compare_To_Constant17_out1 <= '1' WHEN HDL_Counter4_out1 = to_unsigned(16#C8#, 8) ELSE
      '0';

  Logical_Operator34_out1 <= Logical_Operator_out1 OR Compare_To_Constant17_out1;

  SA12_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      SA12_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND Logical_Operator34_out1 = '1' THEN
        SA12_out1 <= Switch8_out1;
      END IF;
    END IF;
  END PROCESS SA12_process;


  Strob <= SA12_out1;

END rtl;

