-- -------------------------------------------------------------
-- 
-- File Name: D:\Matlab_Vhd\smartCart\OTLADKA\hdlsrc\smartCart4_1_work\head_ip_axi_lite.vhd
-- Created: 2016-07-21 09:50:09
-- 
-- Generated by MATLAB 9.0 and HDL Coder 3.8
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: head_ip_axi_lite
-- Source Path: head_ip/head_ip_axi_lite
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY head_ip_axi_lite IS
  PORT( reset                             :   IN    std_logic;
        AXI4_Lite_ACLK                    :   IN    std_logic;  -- ufix1
        AXI4_Lite_ARESETN                 :   IN    std_logic;  -- ufix1
        AXI4_Lite_AWADDR                  :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
        AXI4_Lite_AWVALID                 :   IN    std_logic;  -- ufix1
        AXI4_Lite_WDATA                   :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        AXI4_Lite_WSTRB                   :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        AXI4_Lite_WVALID                  :   IN    std_logic;  -- ufix1
        AXI4_Lite_BREADY                  :   IN    std_logic;  -- ufix1
        AXI4_Lite_ARADDR                  :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
        AXI4_Lite_ARVALID                 :   IN    std_logic;  -- ufix1
        AXI4_Lite_RREADY                  :   IN    std_logic;  -- ufix1
        read_Out1                         :   IN    std_logic_vector(7 DOWNTO 0);  -- ufix8
        read_Out2                         :   IN    std_logic_vector(7 DOWNTO 0);  -- ufix8
        read_Out3                         :   IN    std_logic_vector(7 DOWNTO 0);  -- ufix8
        read_Out4                         :   IN    std_logic_vector(7 DOWNTO 0);  -- ufix8
        read_Out5                         :   IN    std_logic_vector(7 DOWNTO 0);  -- ufix8
        read_Out6                         :   IN    std_logic_vector(7 DOWNTO 0);  -- ufix8
        read_Out7                         :   IN    std_logic_vector(7 DOWNTO 0);  -- ufix8
        read_Out8                         :   IN    std_logic_vector(7 DOWNTO 0);  -- ufix8
        read_status                       :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        AXI4_Lite_AWREADY                 :   OUT   std_logic;  -- ufix1
        AXI4_Lite_WREADY                  :   OUT   std_logic;  -- ufix1
        AXI4_Lite_BRESP                   :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
        AXI4_Lite_BVALID                  :   OUT   std_logic;  -- ufix1
        AXI4_Lite_ARREADY                 :   OUT   std_logic;  -- ufix1
        AXI4_Lite_RDATA                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        AXI4_Lite_RRESP                   :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
        AXI4_Lite_RVALID                  :   OUT   std_logic;  -- ufix1
        write_axi_enable                  :   OUT   std_logic;  -- ufix1
        write_comanda                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        write_data_in_1                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        write_data_in_2                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        write_data_in_3                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        write_data_in_4                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        write_data_in_5                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        write_data_in_6                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        write_data_in_7                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        write_data_in_8                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        reset_internal                    :   OUT   std_logic  -- ufix1
        );
END head_ip_axi_lite;


ARCHITECTURE rtl OF head_ip_axi_lite IS

  -- Component Declarations
  COMPONENT head_ip_addr_decoder
    PORT( clk                             :   IN    std_logic;  -- ufix1
          reset                           :   IN    std_logic;
          data_write                      :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          addr_sel                        :   IN    std_logic_vector(13 DOWNTO 0);  -- ufix14
          wr_enb                          :   IN    std_logic;  -- ufix1
          rd_enb                          :   IN    std_logic;  -- ufix1
          read_Out1                       :   IN    std_logic_vector(7 DOWNTO 0);  -- ufix8
          read_Out2                       :   IN    std_logic_vector(7 DOWNTO 0);  -- ufix8
          read_Out3                       :   IN    std_logic_vector(7 DOWNTO 0);  -- ufix8
          read_Out4                       :   IN    std_logic_vector(7 DOWNTO 0);  -- ufix8
          read_Out5                       :   IN    std_logic_vector(7 DOWNTO 0);  -- ufix8
          read_Out6                       :   IN    std_logic_vector(7 DOWNTO 0);  -- ufix8
          read_Out7                       :   IN    std_logic_vector(7 DOWNTO 0);  -- ufix8
          read_Out8                       :   IN    std_logic_vector(7 DOWNTO 0);  -- ufix8
          read_status                     :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          data_read                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          write_axi_enable                :   OUT   std_logic;  -- ufix1
          write_comanda                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          write_data_in_1                 :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          write_data_in_2                 :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          write_data_in_3                 :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          write_data_in_4                 :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          write_data_in_5                 :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          write_data_in_6                 :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          write_data_in_7                 :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          write_data_in_8                 :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32
          );
  END COMPONENT;

  COMPONENT head_ip_axi_lite_module
    PORT( clk                             :   IN    std_logic;  -- ufix1
          AXI4_Lite_ARESETN               :   IN    std_logic;  -- ufix1
          AXI4_Lite_AWADDR                :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
          AXI4_Lite_AWVALID               :   IN    std_logic;  -- ufix1
          AXI4_Lite_WDATA                 :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          AXI4_Lite_WSTRB                 :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
          AXI4_Lite_WVALID                :   IN    std_logic;  -- ufix1
          AXI4_Lite_BREADY                :   IN    std_logic;  -- ufix1
          AXI4_Lite_ARADDR                :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
          AXI4_Lite_ARVALID               :   IN    std_logic;  -- ufix1
          AXI4_Lite_RREADY                :   IN    std_logic;  -- ufix1
          data_read                       :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          AXI4_Lite_AWREADY               :   OUT   std_logic;  -- ufix1
          AXI4_Lite_WREADY                :   OUT   std_logic;  -- ufix1
          AXI4_Lite_BRESP                 :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
          AXI4_Lite_BVALID                :   OUT   std_logic;  -- ufix1
          AXI4_Lite_ARREADY               :   OUT   std_logic;  -- ufix1
          AXI4_Lite_RDATA                 :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          AXI4_Lite_RRESP                 :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
          AXI4_Lite_RVALID                :   OUT   std_logic;  -- ufix1
          data_write                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          addr_sel                        :   OUT   std_logic_vector(13 DOWNTO 0);  -- ufix14
          wr_enb                          :   OUT   std_logic;  -- ufix1
          rd_enb                          :   OUT   std_logic;  -- ufix1
          reset_internal                  :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : head_ip_addr_decoder
    USE ENTITY work.head_ip_addr_decoder(rtl);

  FOR ALL : head_ip_axi_lite_module
    USE ENTITY work.head_ip_axi_lite_module(rtl);

  -- Signals
  SIGNAL top_data_write                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL top_addr_sel                     : std_logic_vector(13 DOWNTO 0);  -- ufix14
  SIGNAL top_wr_enb                       : std_logic;  -- ufix1
  SIGNAL top_rd_enb                       : std_logic;  -- ufix1
  SIGNAL top_data_read                    : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL write_comanda_tmp                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL write_data_in_1_tmp              : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL write_data_in_2_tmp              : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL write_data_in_3_tmp              : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL write_data_in_4_tmp              : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL write_data_in_5_tmp              : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL write_data_in_6_tmp              : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL write_data_in_7_tmp              : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL write_data_in_8_tmp              : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL AXI4_Lite_BRESP_tmp              : std_logic_vector(1 DOWNTO 0);  -- ufix2
  SIGNAL AXI4_Lite_RDATA_tmp              : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL AXI4_Lite_RRESP_tmp              : std_logic_vector(1 DOWNTO 0);  -- ufix2
  SIGNAL top_reset_internal               : std_logic;  -- ufix1

BEGIN
  u_head_ip_addr_decoder_inst : head_ip_addr_decoder
    PORT MAP( clk => AXI4_Lite_ACLK,  -- ufix1
              reset => reset,
              data_write => top_data_write,  -- ufix32
              addr_sel => top_addr_sel,  -- ufix14
              wr_enb => top_wr_enb,  -- ufix1
              rd_enb => top_rd_enb,  -- ufix1
              read_Out1 => read_Out1,  -- ufix8
              read_Out2 => read_Out2,  -- ufix8
              read_Out3 => read_Out3,  -- ufix8
              read_Out4 => read_Out4,  -- ufix8
              read_Out5 => read_Out5,  -- ufix8
              read_Out6 => read_Out6,  -- ufix8
              read_Out7 => read_Out7,  -- ufix8
              read_Out8 => read_Out8,  -- ufix8
              read_status => read_status,  -- ufix32
              data_read => top_data_read,  -- ufix32
              write_axi_enable => write_axi_enable,  -- ufix1
              write_comanda => write_comanda_tmp,  -- ufix32
              write_data_in_1 => write_data_in_1_tmp,  -- ufix32
              write_data_in_2 => write_data_in_2_tmp,  -- ufix32
              write_data_in_3 => write_data_in_3_tmp,  -- ufix32
              write_data_in_4 => write_data_in_4_tmp,  -- ufix32
              write_data_in_5 => write_data_in_5_tmp,  -- ufix32
              write_data_in_6 => write_data_in_6_tmp,  -- ufix32
              write_data_in_7 => write_data_in_7_tmp,  -- ufix32
              write_data_in_8 => write_data_in_8_tmp  -- ufix32
              );

  u_head_ip_axi_lite_module_inst : head_ip_axi_lite_module
    PORT MAP( clk => AXI4_Lite_ACLK,  -- ufix1
              AXI4_Lite_ARESETN => AXI4_Lite_ARESETN,  -- ufix1
              AXI4_Lite_AWADDR => AXI4_Lite_AWADDR,  -- ufix16
              AXI4_Lite_AWVALID => AXI4_Lite_AWVALID,  -- ufix1
              AXI4_Lite_WDATA => AXI4_Lite_WDATA,  -- ufix32
              AXI4_Lite_WSTRB => AXI4_Lite_WSTRB,  -- ufix4
              AXI4_Lite_WVALID => AXI4_Lite_WVALID,  -- ufix1
              AXI4_Lite_BREADY => AXI4_Lite_BREADY,  -- ufix1
              AXI4_Lite_ARADDR => AXI4_Lite_ARADDR,  -- ufix16
              AXI4_Lite_ARVALID => AXI4_Lite_ARVALID,  -- ufix1
              AXI4_Lite_RREADY => AXI4_Lite_RREADY,  -- ufix1
              data_read => top_data_read,  -- ufix32
              AXI4_Lite_AWREADY => AXI4_Lite_AWREADY,  -- ufix1
              AXI4_Lite_WREADY => AXI4_Lite_WREADY,  -- ufix1
              AXI4_Lite_BRESP => AXI4_Lite_BRESP_tmp,  -- ufix2
              AXI4_Lite_BVALID => AXI4_Lite_BVALID,  -- ufix1
              AXI4_Lite_ARREADY => AXI4_Lite_ARREADY,  -- ufix1
              AXI4_Lite_RDATA => AXI4_Lite_RDATA_tmp,  -- ufix32
              AXI4_Lite_RRESP => AXI4_Lite_RRESP_tmp,  -- ufix2
              AXI4_Lite_RVALID => AXI4_Lite_RVALID,  -- ufix1
              data_write => top_data_write,  -- ufix32
              addr_sel => top_addr_sel,  -- ufix14
              wr_enb => top_wr_enb,  -- ufix1
              rd_enb => top_rd_enb,  -- ufix1
              reset_internal => top_reset_internal  -- ufix1
              );

  reset_internal <= top_reset_internal;

  AXI4_Lite_BRESP <= AXI4_Lite_BRESP_tmp;

  AXI4_Lite_RDATA <= AXI4_Lite_RDATA_tmp;

  AXI4_Lite_RRESP <= AXI4_Lite_RRESP_tmp;

  write_comanda <= write_comanda_tmp;

  write_data_in_1 <= write_data_in_1_tmp;

  write_data_in_2 <= write_data_in_2_tmp;

  write_data_in_3 <= write_data_in_3_tmp;

  write_data_in_4 <= write_data_in_4_tmp;

  write_data_in_5 <= write_data_in_5_tmp;

  write_data_in_6 <= write_data_in_6_tmp;

  write_data_in_7 <= write_data_in_7_tmp;

  write_data_in_8 <= write_data_in_8_tmp;

END rtl;

