-- -------------------------------------------------------------
-- 
-- File Name: D:\Matlab_Vhd\smartCart\OTLADKA\hdlsrc\smartCart5_1work\head_ip_src_head.vhd
-- Created: 2016-07-28 11:38:54
-- 
-- Generated by MATLAB 9.0 and HDL Coder 3.8
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1
-- Target subsystem base rate: 1
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        1
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- signals                       ce_out        1
-- I0_OUT                        ce_out        1
-- strob                         ce_out        1
-- Out1                          ce_out        1
-- Out2                          ce_out        1
-- Out3                          ce_out        1
-- Out4                          ce_out        1
-- Out5                          ce_out        1
-- Out6                          ce_out        1
-- Out7                          ce_out        1
-- Out8                          ce_out        1
-- irq                           ce_out        1
-- status                        ce_out        1
-- trans_io                      ce_out        1
-- switch_io                     ce_out        1
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: head_ip_src_head
-- Source Path: smartCart5_1work/head
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.head_ip_src_head_pkg.ALL;

ENTITY head_ip_src_head IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        comanda                           :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        IO                                :   IN    std_logic;
        data_in_1                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_2                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_3                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_4                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_5                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_6                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_7                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_8                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_9                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_10                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_11                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_12                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_13                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_14                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_15                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_16                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_17                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_18                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_19                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_20                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_21                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_22                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_23                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_24                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_25                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_26                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_27                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_28                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_29                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_30                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_31                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_32                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_33                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_34                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_35                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_36                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_37                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_38                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_39                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_40                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_41                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_42                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_43                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_44                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_45                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_46                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_47                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_48                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_49                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_50                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_51                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_52                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_53                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_54                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_55                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_56                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_57                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_58                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_59                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_60                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_61                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_62                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_63                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        data_in_64                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        Time_pause                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        Time_reciv                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        Time_transmit                     :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        Time_interval                     :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        Time_transition                   :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        ce_out                            :   OUT   std_logic;
        signals                           :   OUT   std_logic_vector(2 DOWNTO 0);  -- sfix3
        I0_OUT                            :   OUT   std_logic;
        strob                             :   OUT   std_logic;
        Out1                              :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        Out2                              :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        Out3                              :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        Out4                              :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        Out5                              :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        Out6                              :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        Out7                              :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        Out8                              :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        irq                               :   OUT   std_logic;
        status                            :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        trans_io                          :   OUT   std_logic;
        switch_io                         :   OUT   std_logic
        );
END head_ip_src_head;


ARCHITECTURE rtl OF head_ip_src_head IS

  -- Component Declarations
  COMPONENT head_ip_src_DEMUX
    PORT( COMMANDA                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          start                           :   OUT   std_logic;
          stop                            :   OUT   std_logic;
          RD_WR                           :   OUT   std_logic;
          STEP                            :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
          RST_IRQ                         :   OUT   std_logic;
          Number_write_byte               :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
          ON_TRANSMITE                    :   OUT   std_logic;
          ON_RECIVER                      :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT head_ip_src_Interface
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          IO                              :   IN    std_logic;
          START                           :   IN    std_logic;
          STOP                            :   IN    std_logic;
          signals2                        :   OUT   std_logic_vector(2 DOWNTO 0);  -- sfix3
          Out3                            :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT head_ip_src_Transmit
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          addrIN                          :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          dataIN                          :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          time_recive                     :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          transmite_on                    :   IN    std_logic;
          DataOUT                         :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          addrOUT                         :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
          IO                              :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT head_ip_src_MUX
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          ADR1                            :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          ADR2                            :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          mADR3                           :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          Data1                           :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          Data2                           :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          mData3                          :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          DataOut                         :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          AdrOut                          :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
          );
  END COMPONENT;

  COMPONENT head_ip_src_Manager
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          AdrrIN                          :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          DataIN                          :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          Start                           :   IN    std_logic;
          Stop                            :   IN    std_logic;
          RD                              :   IN    std_logic;
          STEP                            :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          RST_IRQ                         :   IN    std_logic;
          Number_write_byte               :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          ON_TRANSMITE                    :   IN    std_logic;
          time_pause                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_0                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_1                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_2                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_3                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_4                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_5                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_6                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_7                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_8                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_9                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_10                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_11                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_12                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_13                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_14                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_15                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_16                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_17                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_18                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_19                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_20                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_21                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_22                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_23                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_24                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_25                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_26                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_27                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_28                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_29                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_30                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_31                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_32                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_33                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_34                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_35                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_36                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_37                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_38                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_39                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_40                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_41                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_42                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_43                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_44                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_45                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_46                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_47                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_48                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_49                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_50                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_51                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_52                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_53                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_54                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_55                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_56                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_57                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_58                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_59                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_60                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_61                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_62                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          data_in_63                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          addrout                         :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
          DATA_OUT                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          Out1                            :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
          Out2                            :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
          Out3                            :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
          Out4                            :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
          Out5                            :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
          Out6                            :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
          Out7                            :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
          Out8                            :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
          irq                             :   OUT   std_logic;
          addr_mux                        :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
          data_mux                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          STATUS                          :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          rd_switch                       :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT head_ip_src_Reciver
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          RST                             :   IN    std_logic_vector(2 DOWNTO 0);  -- sfix3
          IO                              :   IN    std_logic;
          STOP                            :   IN    std_logic;
          adr_IN                          :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          data_in                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          ON_RECIVER                      :   IN    std_logic;
          TimOUT                          :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          time_transmite                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          time_transition                 :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          AddrOUT                         :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
          STATUS                          :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          Strob                           :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : head_ip_src_DEMUX
    USE ENTITY work.head_ip_src_DEMUX(rtl);

  FOR ALL : head_ip_src_Interface
    USE ENTITY work.head_ip_src_Interface(rtl);

  FOR ALL : head_ip_src_Transmit
    USE ENTITY work.head_ip_src_Transmit(rtl);

  FOR ALL : head_ip_src_MUX
    USE ENTITY work.head_ip_src_MUX(rtl);

  FOR ALL : head_ip_src_Manager
    USE ENTITY work.head_ip_src_Manager(rtl);

  FOR ALL : head_ip_src_Reciver
    USE ENTITY work.head_ip_src_Reciver(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL Delay1_out1                      : std_logic;
  SIGNAL comanda_unsigned                 : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay_out1                       : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL DEMUX_out1                       : std_logic;
  SIGNAL DEMUX_out2                       : std_logic;
  SIGNAL DEMUX_out3                       : std_logic;
  SIGNAL DEMUX_out4                       : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL DEMUX_out5                       : std_logic;
  SIGNAL DEMUX_out6                       : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL DEMUX_out7                       : std_logic;
  SIGNAL DEMUX_out8                       : std_logic;
  SIGNAL Interface_out1                   : std_logic_vector(2 DOWNTO 0);  -- ufix3
  SIGNAL Interface_out2                   : std_logic;
  SIGNAL Time_reciv_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay12_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Time_interval_unsigned           : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay13_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_1_unsigned               : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay2_out1                      : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_2_unsigned               : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay3_out1                      : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_3_unsigned               : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay4_out1                      : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_4_unsigned               : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay5_out1                      : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_5_unsigned               : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay6_out1                      : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_6_unsigned               : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay7_out1                      : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_7_unsigned               : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay8_out1                      : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_8_unsigned               : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay9_out1                      : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_9_unsigned               : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay14_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_10_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay15_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_11_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay16_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_12_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay17_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_13_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay18_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_14_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay19_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_15_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay20_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_16_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay21_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_17_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay22_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_18_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay23_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_19_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay24_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_20_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay25_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_21_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay26_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_22_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay27_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_23_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay28_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_24_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay29_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_25_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay30_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_26_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay31_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_27_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay32_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_28_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay33_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_29_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay34_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_30_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay35_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_31_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay36_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_32_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay37_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_33_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay38_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_34_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay39_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_35_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay40_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_36_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay41_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_37_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay42_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_38_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay43_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_39_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay44_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_40_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay45_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_41_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay46_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_42_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay47_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_43_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay48_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_44_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay49_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_45_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay50_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_46_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay51_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_47_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay52_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_48_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay53_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_49_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay54_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_50_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay55_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_51_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay56_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_52_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay57_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_53_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay58_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_54_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay59_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_55_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay60_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_56_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay61_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_57_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay62_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_58_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay63_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_59_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay64_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_60_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay65_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_61_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay66_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_62_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay67_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_63_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay68_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL data_in_64_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay69_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Time_pause_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay10_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Time_transmit_unsigned           : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay11_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Time_transition_unsigned         : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay70_reg                      : vector_of_unsigned32(0 TO 1);  -- ufix32 [2]
  SIGNAL Delay70_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Manager_out1                     : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL Manager_out2                     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Transmit_out1                    : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Transmit_out2                    : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL Transmit_out3                    : std_logic;
  SIGNAL Reciver_out1                     : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL Manager_out12                    : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL Reciver_out2                     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Manager_out13                    : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL MUX_out1                         : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL MUX_out2                         : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL Manager_out3                     : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL Manager_out4                     : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL Manager_out5                     : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL Manager_out6                     : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL Manager_out7                     : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL Manager_out8                     : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL Manager_out9                     : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL Manager_out10                    : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL Manager_out11                    : std_logic;
  SIGNAL Manager_out14                    : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Manager_out15                    : std_logic;
  SIGNAL Reciver_out3                     : std_logic;
  SIGNAL Logical_Operator_out1            : std_logic;

BEGIN
  -- Переключатель адрес 4
  -- 
  -- Приёмник адрес (1)  
  -- 1-2 бит   тип сообщения  если  1 то соостояние счётчика  2 считыные байт байты
  -- 3-11 бит значение сяётчика адреса 
  -- 12-20 бит считанный байт 

  u_DEMUX : head_ip_src_DEMUX
    PORT MAP( COMMANDA => std_logic_vector(Delay_out1),  -- uint32
              start => DEMUX_out1,
              stop => DEMUX_out2,
              RD_WR => DEMUX_out3,
              STEP => DEMUX_out4,  -- uint8
              RST_IRQ => DEMUX_out5,
              Number_write_byte => DEMUX_out6,  -- uint8
              ON_TRANSMITE => DEMUX_out7,
              ON_RECIVER => DEMUX_out8
              );

  u_Interface : head_ip_src_Interface
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              IO => Delay1_out1,
              START => DEMUX_out1,
              STOP => DEMUX_out2,
              signals2 => Interface_out1,  -- sfix3
              Out3 => Interface_out2
              );

  u_Transmit : head_ip_src_Transmit
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              addrIN => Manager_out1,  -- uint8
              dataIN => Manager_out2,  -- uint32
              time_recive => std_logic_vector(Delay12_out1),  -- uint32
              transmite_on => DEMUX_out7,
              DataOUT => Transmit_out1,  -- uint32
              addrOUT => Transmit_out2,  -- uint8
              IO => Transmit_out3
              );

  u_MUX : head_ip_src_MUX
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              ADR1 => Reciver_out1,  -- uint8
              ADR2 => Transmit_out2,  -- uint8
              mADR3 => Manager_out12,  -- uint8
              Data1 => Reciver_out2,  -- uint32
              Data2 => Transmit_out1,  -- uint32
              mData3 => Manager_out13,  -- uint32
              DataOut => MUX_out1,  -- uint32
              AdrOut => MUX_out2  -- uint8
              );

  u_Manager : head_ip_src_Manager
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              AdrrIN => MUX_out2,  -- uint8
              DataIN => MUX_out1,  -- uint32
              Start => DEMUX_out1,
              Stop => DEMUX_out2,
              RD => DEMUX_out3,
              STEP => DEMUX_out4,  -- uint8
              RST_IRQ => DEMUX_out5,
              Number_write_byte => DEMUX_out6,  -- uint8
              ON_TRANSMITE => DEMUX_out7,
              time_pause => std_logic_vector(Delay13_out1),  -- uint32
              data_in_0 => std_logic_vector(Delay2_out1),  -- uint32
              data_in_1 => std_logic_vector(Delay3_out1),  -- uint32
              data_in_2 => std_logic_vector(Delay4_out1),  -- uint32
              data_in_3 => std_logic_vector(Delay5_out1),  -- uint32
              data_in_4 => std_logic_vector(Delay6_out1),  -- uint32
              data_in_5 => std_logic_vector(Delay7_out1),  -- uint32
              data_in_6 => std_logic_vector(Delay8_out1),  -- uint32
              data_in_7 => std_logic_vector(Delay9_out1),  -- uint32
              data_in_8 => std_logic_vector(Delay14_out1),  -- uint32
              data_in_9 => std_logic_vector(Delay15_out1),  -- uint32
              data_in_10 => std_logic_vector(Delay16_out1),  -- uint32
              data_in_11 => std_logic_vector(Delay17_out1),  -- uint32
              data_in_12 => std_logic_vector(Delay18_out1),  -- uint32
              data_in_13 => std_logic_vector(Delay19_out1),  -- uint32
              data_in_14 => std_logic_vector(Delay20_out1),  -- uint32
              data_in_15 => std_logic_vector(Delay21_out1),  -- uint32
              data_in_16 => std_logic_vector(Delay22_out1),  -- uint32
              data_in_17 => std_logic_vector(Delay23_out1),  -- uint32
              data_in_18 => std_logic_vector(Delay24_out1),  -- uint32
              data_in_19 => std_logic_vector(Delay25_out1),  -- uint32
              data_in_20 => std_logic_vector(Delay26_out1),  -- uint32
              data_in_21 => std_logic_vector(Delay27_out1),  -- uint32
              data_in_22 => std_logic_vector(Delay28_out1),  -- uint32
              data_in_23 => std_logic_vector(Delay29_out1),  -- uint32
              data_in_24 => std_logic_vector(Delay30_out1),  -- uint32
              data_in_25 => std_logic_vector(Delay31_out1),  -- uint32
              data_in_26 => std_logic_vector(Delay32_out1),  -- uint32
              data_in_27 => std_logic_vector(Delay33_out1),  -- uint32
              data_in_28 => std_logic_vector(Delay34_out1),  -- uint32
              data_in_29 => std_logic_vector(Delay35_out1),  -- uint32
              data_in_30 => std_logic_vector(Delay36_out1),  -- uint32
              data_in_31 => std_logic_vector(Delay37_out1),  -- uint32
              data_in_32 => std_logic_vector(Delay38_out1),  -- uint32
              data_in_33 => std_logic_vector(Delay39_out1),  -- uint32
              data_in_34 => std_logic_vector(Delay40_out1),  -- uint32
              data_in_35 => std_logic_vector(Delay41_out1),  -- uint32
              data_in_36 => std_logic_vector(Delay42_out1),  -- uint32
              data_in_37 => std_logic_vector(Delay43_out1),  -- uint32
              data_in_38 => std_logic_vector(Delay44_out1),  -- uint32
              data_in_39 => std_logic_vector(Delay45_out1),  -- uint32
              data_in_40 => std_logic_vector(Delay46_out1),  -- uint32
              data_in_41 => std_logic_vector(Delay47_out1),  -- uint32
              data_in_42 => std_logic_vector(Delay48_out1),  -- uint32
              data_in_43 => std_logic_vector(Delay49_out1),  -- uint32
              data_in_44 => std_logic_vector(Delay50_out1),  -- uint32
              data_in_45 => std_logic_vector(Delay51_out1),  -- uint32
              data_in_46 => std_logic_vector(Delay52_out1),  -- uint32
              data_in_47 => std_logic_vector(Delay53_out1),  -- uint32
              data_in_48 => std_logic_vector(Delay54_out1),  -- uint32
              data_in_49 => std_logic_vector(Delay55_out1),  -- uint32
              data_in_50 => std_logic_vector(Delay56_out1),  -- uint32
              data_in_51 => std_logic_vector(Delay57_out1),  -- uint32
              data_in_52 => std_logic_vector(Delay58_out1),  -- uint32
              data_in_53 => std_logic_vector(Delay59_out1),  -- uint32
              data_in_54 => std_logic_vector(Delay60_out1),  -- uint32
              data_in_55 => std_logic_vector(Delay61_out1),  -- uint32
              data_in_56 => std_logic_vector(Delay62_out1),  -- uint32
              data_in_57 => std_logic_vector(Delay63_out1),  -- uint32
              data_in_58 => std_logic_vector(Delay64_out1),  -- uint32
              data_in_59 => std_logic_vector(Delay65_out1),  -- uint32
              data_in_60 => std_logic_vector(Delay66_out1),  -- uint32
              data_in_61 => std_logic_vector(Delay67_out1),  -- uint32
              data_in_62 => std_logic_vector(Delay68_out1),  -- uint32
              data_in_63 => std_logic_vector(Delay69_out1),  -- uint32
              addrout => Manager_out1,  -- uint8
              DATA_OUT => Manager_out2,  -- uint32
              Out1 => Manager_out3,  -- uint8
              Out2 => Manager_out4,  -- uint8
              Out3 => Manager_out5,  -- uint8
              Out4 => Manager_out6,  -- uint8
              Out5 => Manager_out7,  -- uint8
              Out6 => Manager_out8,  -- uint8
              Out7 => Manager_out9,  -- uint8
              Out8 => Manager_out10,  -- uint8
              irq => Manager_out11,
              addr_mux => Manager_out12,  -- uint8
              data_mux => Manager_out13,  -- uint32
              STATUS => Manager_out14,  -- uint32
              rd_switch => Manager_out15
              );

  u_Reciver : head_ip_src_Reciver
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              RST => Interface_out1,  -- sfix3
              IO => Delay1_out1,
              STOP => DEMUX_out2,
              adr_IN => Manager_out1,  -- uint8
              data_in => Manager_out2,  -- uint32
              ON_RECIVER => DEMUX_out8,
              TimOUT => std_logic_vector(Delay10_out1),  -- uint32
              time_transmite => std_logic_vector(Delay11_out1),  -- uint32
              time_transition => std_logic_vector(Delay70_out1),  -- uint32
              AddrOUT => Reciver_out1,  -- uint8
              STATUS => Reciver_out2,  -- uint32
              Strob => Reciver_out3
              );

  enb <= clk_enable;

  Delay1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay1_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay1_out1 <= IO;
      END IF;
    END IF;
  END PROCESS Delay1_process;


  comanda_unsigned <= unsigned(comanda);

  Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay_out1 <= comanda_unsigned;
      END IF;
    END IF;
  END PROCESS Delay_process;


  Time_reciv_unsigned <= unsigned(Time_reciv);

  Delay12_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay12_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay12_out1 <= Time_reciv_unsigned;
      END IF;
    END IF;
  END PROCESS Delay12_process;


  Time_interval_unsigned <= unsigned(Time_interval);

  Delay13_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay13_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay13_out1 <= Time_interval_unsigned;
      END IF;
    END IF;
  END PROCESS Delay13_process;


  data_in_1_unsigned <= unsigned(data_in_1);

  Delay2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay2_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay2_out1 <= data_in_1_unsigned;
      END IF;
    END IF;
  END PROCESS Delay2_process;


  data_in_2_unsigned <= unsigned(data_in_2);

  Delay3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay3_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay3_out1 <= data_in_2_unsigned;
      END IF;
    END IF;
  END PROCESS Delay3_process;


  data_in_3_unsigned <= unsigned(data_in_3);

  Delay4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay4_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay4_out1 <= data_in_3_unsigned;
      END IF;
    END IF;
  END PROCESS Delay4_process;


  data_in_4_unsigned <= unsigned(data_in_4);

  Delay5_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay5_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay5_out1 <= data_in_4_unsigned;
      END IF;
    END IF;
  END PROCESS Delay5_process;


  data_in_5_unsigned <= unsigned(data_in_5);

  Delay6_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay6_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay6_out1 <= data_in_5_unsigned;
      END IF;
    END IF;
  END PROCESS Delay6_process;


  data_in_6_unsigned <= unsigned(data_in_6);

  Delay7_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay7_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay7_out1 <= data_in_6_unsigned;
      END IF;
    END IF;
  END PROCESS Delay7_process;


  data_in_7_unsigned <= unsigned(data_in_7);

  Delay8_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay8_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay8_out1 <= data_in_7_unsigned;
      END IF;
    END IF;
  END PROCESS Delay8_process;


  data_in_8_unsigned <= unsigned(data_in_8);

  Delay9_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay9_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay9_out1 <= data_in_8_unsigned;
      END IF;
    END IF;
  END PROCESS Delay9_process;


  data_in_9_unsigned <= unsigned(data_in_9);

  Delay14_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay14_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay14_out1 <= data_in_9_unsigned;
      END IF;
    END IF;
  END PROCESS Delay14_process;


  data_in_10_unsigned <= unsigned(data_in_10);

  Delay15_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay15_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay15_out1 <= data_in_10_unsigned;
      END IF;
    END IF;
  END PROCESS Delay15_process;


  data_in_11_unsigned <= unsigned(data_in_11);

  Delay16_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay16_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay16_out1 <= data_in_11_unsigned;
      END IF;
    END IF;
  END PROCESS Delay16_process;


  data_in_12_unsigned <= unsigned(data_in_12);

  Delay17_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay17_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay17_out1 <= data_in_12_unsigned;
      END IF;
    END IF;
  END PROCESS Delay17_process;


  data_in_13_unsigned <= unsigned(data_in_13);

  Delay18_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay18_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay18_out1 <= data_in_13_unsigned;
      END IF;
    END IF;
  END PROCESS Delay18_process;


  data_in_14_unsigned <= unsigned(data_in_14);

  Delay19_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay19_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay19_out1 <= data_in_14_unsigned;
      END IF;
    END IF;
  END PROCESS Delay19_process;


  data_in_15_unsigned <= unsigned(data_in_15);

  Delay20_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay20_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay20_out1 <= data_in_15_unsigned;
      END IF;
    END IF;
  END PROCESS Delay20_process;


  data_in_16_unsigned <= unsigned(data_in_16);

  Delay21_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay21_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay21_out1 <= data_in_16_unsigned;
      END IF;
    END IF;
  END PROCESS Delay21_process;


  data_in_17_unsigned <= unsigned(data_in_17);

  Delay22_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay22_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay22_out1 <= data_in_17_unsigned;
      END IF;
    END IF;
  END PROCESS Delay22_process;


  data_in_18_unsigned <= unsigned(data_in_18);

  Delay23_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay23_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay23_out1 <= data_in_18_unsigned;
      END IF;
    END IF;
  END PROCESS Delay23_process;


  data_in_19_unsigned <= unsigned(data_in_19);

  Delay24_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay24_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay24_out1 <= data_in_19_unsigned;
      END IF;
    END IF;
  END PROCESS Delay24_process;


  data_in_20_unsigned <= unsigned(data_in_20);

  Delay25_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay25_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay25_out1 <= data_in_20_unsigned;
      END IF;
    END IF;
  END PROCESS Delay25_process;


  data_in_21_unsigned <= unsigned(data_in_21);

  Delay26_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay26_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay26_out1 <= data_in_21_unsigned;
      END IF;
    END IF;
  END PROCESS Delay26_process;


  data_in_22_unsigned <= unsigned(data_in_22);

  Delay27_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay27_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay27_out1 <= data_in_22_unsigned;
      END IF;
    END IF;
  END PROCESS Delay27_process;


  data_in_23_unsigned <= unsigned(data_in_23);

  Delay28_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay28_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay28_out1 <= data_in_23_unsigned;
      END IF;
    END IF;
  END PROCESS Delay28_process;


  data_in_24_unsigned <= unsigned(data_in_24);

  Delay29_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay29_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay29_out1 <= data_in_24_unsigned;
      END IF;
    END IF;
  END PROCESS Delay29_process;


  data_in_25_unsigned <= unsigned(data_in_25);

  Delay30_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay30_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay30_out1 <= data_in_25_unsigned;
      END IF;
    END IF;
  END PROCESS Delay30_process;


  data_in_26_unsigned <= unsigned(data_in_26);

  Delay31_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay31_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay31_out1 <= data_in_26_unsigned;
      END IF;
    END IF;
  END PROCESS Delay31_process;


  data_in_27_unsigned <= unsigned(data_in_27);

  Delay32_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay32_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay32_out1 <= data_in_27_unsigned;
      END IF;
    END IF;
  END PROCESS Delay32_process;


  data_in_28_unsigned <= unsigned(data_in_28);

  Delay33_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay33_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay33_out1 <= data_in_28_unsigned;
      END IF;
    END IF;
  END PROCESS Delay33_process;


  data_in_29_unsigned <= unsigned(data_in_29);

  Delay34_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay34_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay34_out1 <= data_in_29_unsigned;
      END IF;
    END IF;
  END PROCESS Delay34_process;


  data_in_30_unsigned <= unsigned(data_in_30);

  Delay35_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay35_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay35_out1 <= data_in_30_unsigned;
      END IF;
    END IF;
  END PROCESS Delay35_process;


  data_in_31_unsigned <= unsigned(data_in_31);

  Delay36_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay36_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay36_out1 <= data_in_31_unsigned;
      END IF;
    END IF;
  END PROCESS Delay36_process;


  data_in_32_unsigned <= unsigned(data_in_32);

  Delay37_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay37_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay37_out1 <= data_in_32_unsigned;
      END IF;
    END IF;
  END PROCESS Delay37_process;


  data_in_33_unsigned <= unsigned(data_in_33);

  Delay38_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay38_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay38_out1 <= data_in_33_unsigned;
      END IF;
    END IF;
  END PROCESS Delay38_process;


  data_in_34_unsigned <= unsigned(data_in_34);

  Delay39_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay39_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay39_out1 <= data_in_34_unsigned;
      END IF;
    END IF;
  END PROCESS Delay39_process;


  data_in_35_unsigned <= unsigned(data_in_35);

  Delay40_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay40_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay40_out1 <= data_in_35_unsigned;
      END IF;
    END IF;
  END PROCESS Delay40_process;


  data_in_36_unsigned <= unsigned(data_in_36);

  Delay41_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay41_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay41_out1 <= data_in_36_unsigned;
      END IF;
    END IF;
  END PROCESS Delay41_process;


  data_in_37_unsigned <= unsigned(data_in_37);

  Delay42_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay42_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay42_out1 <= data_in_37_unsigned;
      END IF;
    END IF;
  END PROCESS Delay42_process;


  data_in_38_unsigned <= unsigned(data_in_38);

  Delay43_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay43_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay43_out1 <= data_in_38_unsigned;
      END IF;
    END IF;
  END PROCESS Delay43_process;


  data_in_39_unsigned <= unsigned(data_in_39);

  Delay44_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay44_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay44_out1 <= data_in_39_unsigned;
      END IF;
    END IF;
  END PROCESS Delay44_process;


  data_in_40_unsigned <= unsigned(data_in_40);

  Delay45_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay45_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay45_out1 <= data_in_40_unsigned;
      END IF;
    END IF;
  END PROCESS Delay45_process;


  data_in_41_unsigned <= unsigned(data_in_41);

  Delay46_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay46_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay46_out1 <= data_in_41_unsigned;
      END IF;
    END IF;
  END PROCESS Delay46_process;


  data_in_42_unsigned <= unsigned(data_in_42);

  Delay47_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay47_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay47_out1 <= data_in_42_unsigned;
      END IF;
    END IF;
  END PROCESS Delay47_process;


  data_in_43_unsigned <= unsigned(data_in_43);

  Delay48_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay48_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay48_out1 <= data_in_43_unsigned;
      END IF;
    END IF;
  END PROCESS Delay48_process;


  data_in_44_unsigned <= unsigned(data_in_44);

  Delay49_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay49_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay49_out1 <= data_in_44_unsigned;
      END IF;
    END IF;
  END PROCESS Delay49_process;


  data_in_45_unsigned <= unsigned(data_in_45);

  Delay50_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay50_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay50_out1 <= data_in_45_unsigned;
      END IF;
    END IF;
  END PROCESS Delay50_process;


  data_in_46_unsigned <= unsigned(data_in_46);

  Delay51_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay51_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay51_out1 <= data_in_46_unsigned;
      END IF;
    END IF;
  END PROCESS Delay51_process;


  data_in_47_unsigned <= unsigned(data_in_47);

  Delay52_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay52_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay52_out1 <= data_in_47_unsigned;
      END IF;
    END IF;
  END PROCESS Delay52_process;


  data_in_48_unsigned <= unsigned(data_in_48);

  Delay53_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay53_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay53_out1 <= data_in_48_unsigned;
      END IF;
    END IF;
  END PROCESS Delay53_process;


  data_in_49_unsigned <= unsigned(data_in_49);

  Delay54_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay54_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay54_out1 <= data_in_49_unsigned;
      END IF;
    END IF;
  END PROCESS Delay54_process;


  data_in_50_unsigned <= unsigned(data_in_50);

  Delay55_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay55_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay55_out1 <= data_in_50_unsigned;
      END IF;
    END IF;
  END PROCESS Delay55_process;


  data_in_51_unsigned <= unsigned(data_in_51);

  Delay56_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay56_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay56_out1 <= data_in_51_unsigned;
      END IF;
    END IF;
  END PROCESS Delay56_process;


  data_in_52_unsigned <= unsigned(data_in_52);

  Delay57_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay57_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay57_out1 <= data_in_52_unsigned;
      END IF;
    END IF;
  END PROCESS Delay57_process;


  data_in_53_unsigned <= unsigned(data_in_53);

  Delay58_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay58_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay58_out1 <= data_in_53_unsigned;
      END IF;
    END IF;
  END PROCESS Delay58_process;


  data_in_54_unsigned <= unsigned(data_in_54);

  Delay59_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay59_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay59_out1 <= data_in_54_unsigned;
      END IF;
    END IF;
  END PROCESS Delay59_process;


  data_in_55_unsigned <= unsigned(data_in_55);

  Delay60_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay60_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay60_out1 <= data_in_55_unsigned;
      END IF;
    END IF;
  END PROCESS Delay60_process;


  data_in_56_unsigned <= unsigned(data_in_56);

  Delay61_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay61_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay61_out1 <= data_in_56_unsigned;
      END IF;
    END IF;
  END PROCESS Delay61_process;


  data_in_57_unsigned <= unsigned(data_in_57);

  Delay62_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay62_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay62_out1 <= data_in_57_unsigned;
      END IF;
    END IF;
  END PROCESS Delay62_process;


  data_in_58_unsigned <= unsigned(data_in_58);

  Delay63_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay63_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay63_out1 <= data_in_58_unsigned;
      END IF;
    END IF;
  END PROCESS Delay63_process;


  data_in_59_unsigned <= unsigned(data_in_59);

  Delay64_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay64_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay64_out1 <= data_in_59_unsigned;
      END IF;
    END IF;
  END PROCESS Delay64_process;


  data_in_60_unsigned <= unsigned(data_in_60);

  Delay65_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay65_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay65_out1 <= data_in_60_unsigned;
      END IF;
    END IF;
  END PROCESS Delay65_process;


  data_in_61_unsigned <= unsigned(data_in_61);

  Delay66_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay66_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay66_out1 <= data_in_61_unsigned;
      END IF;
    END IF;
  END PROCESS Delay66_process;


  data_in_62_unsigned <= unsigned(data_in_62);

  Delay67_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay67_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay67_out1 <= data_in_62_unsigned;
      END IF;
    END IF;
  END PROCESS Delay67_process;


  data_in_63_unsigned <= unsigned(data_in_63);

  Delay68_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay68_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay68_out1 <= data_in_63_unsigned;
      END IF;
    END IF;
  END PROCESS Delay68_process;


  data_in_64_unsigned <= unsigned(data_in_64);

  Delay69_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay69_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay69_out1 <= data_in_64_unsigned;
      END IF;
    END IF;
  END PROCESS Delay69_process;


  Time_pause_unsigned <= unsigned(Time_pause);

  Delay10_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay10_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay10_out1 <= Time_pause_unsigned;
      END IF;
    END IF;
  END PROCESS Delay10_process;


  Time_transmit_unsigned <= unsigned(Time_transmit);

  Delay11_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay11_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay11_out1 <= Time_transmit_unsigned;
      END IF;
    END IF;
  END PROCESS Delay11_process;


  Time_transition_unsigned <= unsigned(Time_transition);

  Delay70_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay70_reg <= (OTHERS => to_unsigned(0, 32));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay70_reg(0) <= Time_transition_unsigned;
        Delay70_reg(1) <= Delay70_reg(0);
      END IF;
    END IF;
  END PROCESS Delay70_process;

  Delay70_out1 <= Delay70_reg(1);

  Logical_Operator_out1 <= DEMUX_out3 OR Manager_out15;

  ce_out <= clk_enable;

  signals <= Interface_out1;

  I0_OUT <= Interface_out2;

  strob <= Reciver_out3;

  Out1 <= Manager_out3;

  Out2 <= Manager_out4;

  Out3 <= Manager_out5;

  Out4 <= Manager_out6;

  Out5 <= Manager_out7;

  Out6 <= Manager_out8;

  Out7 <= Manager_out9;

  Out8 <= Manager_out10;

  irq <= Manager_out11;

  status <= Manager_out14;

  trans_io <= Transmit_out3;

  switch_io <= Logical_Operator_out1;

END rtl;

